### ISSUE TITLE
Reduce I/O by fusing repeated getitems on arrays

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#103]
Consider the following term

```python
    # x[1000:2000][15:20]
    (getitem,
      (getitem, x, (slice(1000, 2000),)),
      slice(15, 20)
```

This is equivalent to the following much faster term

```python
    # x[1015: 1020]
    (getitem, x, (slice(1015, 1020),))
```

This happens a lot when we use `from_array` and then slice

```python
>>> d = da.from_array(x, blockshape=(1000,))  # First round of getitem
>>> d[1015:1020]  # Second round of getitem
```

If we can optimize then we cut down *a lot* on I/O.  This is also pretty typical as people block in a bulk way but pull out thin slices.  This ends up being very important when slicing into large volumetric arrays (e.g. @shoyer 's work with [xray](xray.readthedocs.org)) and gives us a lot of leeway with choosing bad chunk sizes.

I would break this problem into two sub-problems

1.  A function to operate on terms, enacting the transformation shown in the above example, although being aware of multiple slices and possibly integer values as well.  This requires attention to detail but is not very complex from a dask perspective.  If we can get either of them to dive into these problems again @nevermindewe and @PeterDSteinberg have shown talent here.
2.  A function to apply such a transformation within nested terms (e.g. what happens if this subterm is within yet another function call).  This is more in line with previous work done by @eriknw or @jcrist.  In particular in relation to recent work on Rewrite Rules #82 how do we cleanly extend traversing terms and applying general callables?  What's the best way to enable these transformations?

**Comment by shoyer** [comment]
This is actually useful enough that I wrote a whole special class to encapsulate this logic for xray, [`LazilyIndexedArray`](https://github.com/xray/xray/blob/0d164d848401209971ded33aea2880c1fdc892cb/xray/core/indexing.py#L226). There may be some relevant logic there for task 1 (e.g., how to slice a slice object).

**Comment by jcrist** [comment]
Well, matching can easily find these terms, `RewriteRule` could be generalized to take in an arbitrary right hand side. If it's a function, it accepts a dict representing the match. If it's a term, a specific subs function is created and linked in, so that rewriting is always match -> validate (for non linear patterns) -> apply func. I have something like this already written up for SymPy, I'll port it over the weekend/early next week.

**Comment by mrocklin** [comment]
Here is a first pass on problem 1

```python
from operator import getitem

def test_fuse_getitem():
    pairs = [((getitem, (getitem, 'x', slice(1000, 2000)), slice(15, 20)),
              (getitem, 'x', slice(1015, 1020))),

             ((getitem, (getitem, 'x', (slice(1000, 2000), slice(100, 200))),
                        (slice(15, 20), slice(50, 60))),
              (getitem, 'x', (slice(1015, 1020), slice(150, 160)))),

             ((getitem, (getitem, 'x', slice(1000, 2000)), 10),
              (getitem, 'x', 1010)),

             ((getitem, (getitem, 'x', (slice(1000, 2000), 10)),
                        (slice(15, 20),)),
              (getitem, 'x', (slice(1015, 1020), 10))),

             ((getitem, (getitem, 'x', (10, slice(1000, 2000))),
                        (slice(15, 20),)),
              (getitem, 'x', (10, slice(1015, 1020))))

        ]

    for inp, expected in pairs:
        result = fuse_getitem(inp)
        assert result == expected


def fuse_getitem(term):
    (_, (_, x, a), b) = term

    c = fuse_slice(a, b)

    return (getitem, x, c)


def normalize_slice(s):
    start, stop, step = s.start, s.stop, s.step
    if start is None:
        start = 0
    if step is None:
        step = 1
    return slice(start, stop, step)

def fuse_slice(a, b):
    if isinstance(a, slice):
        a = normalize_slice(a)
    if isinstance(b, slice):
        b = normalize_slice(b)

    if isinstance(a, slice) and isinstance(b, int):
        return a.start + b*(a.step if a.step is not None else 1)
    if isinstance(a, slice) and isinstance(b, slice):
        start = a.start + a.step * b.start
        if b.stop is not None:
            stop = a.start + a.step * b.step * b.stop
        else:
            stop = None
        if a.stop is not None:
            if stop is not None:
                stop = min(a.stop, stop)
            else:
                stop = a.stop
            stop = stop - ((stop - start) % b.step)
        step = a.step * b.step
        if step == 1:
            step = None
        return slice(start, stop, step)
    if isinstance(a, tuple) and not isinstance(b, tuple):
        b = (b,)
    if isinstance(a, tuple) and isinstance(b, tuple):
        j = 0
        result = list()
        for i in range(len(a)):
            if isinstance(a[i], int):
                result.append(a[i])
                continue
            result.append(fuse_slice(a[i], b[j]))
            j += 1
        return tuple(result)
    raise NotImplementedError()
```

**Comment by mrocklin** [comment]
Doesn't handle the stranger slicing conditions (e.g. negative steps) nor is it exhaustively tested (e.g. steps at all)

**Comment by jcrist** [comment]
Addressed problem 2 with #106. Just make a function that accepts a dict of matches and returns a term, and use it as the rhs of the rule.

**Comment by shoyer** [comment]
@jcrist @mrocklin Very nice!

I have a pretty exhaustive test suite that I wrote for xray -- it basically just checks all permutations of a long set of slices against the output that would be generated from numpy array:
https://github.com/xray/xray/blob/0d164d848401209971ded33aea2880c1fdc892cb/xray/test/test_indexing.py#L85

Happy to help put things together but it looks like you already have a good start.

RE rewrite rules: what about optimizing cases like `x.mean(axis=1)[:5]`? Ideally, there would be some notion of operations that can commute along a given axis.

**Comment by mrocklin** [comment]
I'm fooling around with this in #107 .  Feedback and test cases heartily welcomed there.  It's getting a bit crazy.
