### ISSUE TITLE
Reblocking along some subset of axes

### ISSUE THREAD

**Issue by shoyer** [ContinuumIO/dask#117]
For the user-facing reblock API in xray, I would like to be able to reblock along only some subset of axes, e.g., `ds.reblock(blockshape={'time': 100})` should only modify blockdims along the `time` dimension, even if there are also `latitude` and `longitude` dimensions.

This looks like a little tricky to do with the current reblock API.

Two options:

1. Expose `blockdims_from_blockshape` in the public API. That way, I can calculate blockdims myself, filling in ones I don't want to change.
2. Support providing only some axes to `blockdims` and `blockshape` in `reblock`. For example, to indicate that only axis 0 should be reblocked but others should be left alone (in a 3D array), we could write `blockshape=(100, None, None)` or `blockshape={0: 100}`.

Thoughts?

CC @PeterDSteinberg

**Comment by PeterDSteinberg** [comment]
This seems to be the trick for the near term, but I'll have to think about this more.  I agree it is not straighforward as written.
<pre><code>
import dask.array as da
import numpy as np
n = np.random.uniform(0,1,100).reshape((20,5))
x = da.from_array(n, blockdims=((10,),(2,3)))
# use the existing blockdims
changed_column = x.reblock(blockdims=(x.blockdims[0], (1,1,2,1)))
changed_row = x.reblock(blockdims=((5,2,3), x.blockdims[1]))
</code></pre>

**Comment by shoyer** [comment]
The tricky case is when you want to assign a new *blockshape* only along one dimension. Then you have to use `blockdims_from_blockshape` (or something similar) to turn that blockshape into blockdims.

**Comment by PeterDSteinberg** [comment]
I see better what you are saying.  I think we should make <pre><code>blockdims_from_blockshape</code></pre> able to be imported, and also we should make more options in the reblock method of dask arrays and the reblock function.  The options should support reblocking a subset of the dimensions, specified by either blockdims or blockshape.  I'll work on that soon.

**Comment by shoyer** [comment]
> I'll work on that soon.

Great, I'm looking forward to it. By the way, `reblock` is awesome!
