### ISSUE TITLE
Naive use of da.reblock with blockshape fails

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#124]
A bit of follow on work for reblocking.  The following lines of reblock code seem likely to be typed in by users when they assume that they can provide a blockshape to reblock without a keyword.  Currently this experience yields an uninformative error.

```python
In [1]: import dask.array as da

In [2]: x = da.ones((4, 4), blockshape=(1, 4))

In [3]: y = x.reblock((4, 1))
     28     return [tuple(zip((const,) * (1 + len(bds)),
     29                       list(accumulate(add, (0,) + bds))))
---> 30               for bds in blockdims ]
     31 
     32 

TypeError: object of type 'int' has no len()
```

Probably we should do one of the following

1.  Inspect the first input and decide if we think it's a blockshape (tuple of ints) or a blockdims (tuple of tuples of ints) argument
2.  Raise an informative error.  

cc @PeterDSteinberg

**Comment by shoyer** [comment]
There is the exact same usability issue for `da.from_array`:
```
>>> da.from_array(np.ones((4, 4)), (4, 1))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-241-e8be59764628> in <module>()
----> 1 da.from_array(np.ones((4, 4)), (4, 1))

/Users/shoyer/dev/dask/dask/array/core.pyc in from_array(x, blockdims, blockshape, name, **kwargs)
    797         blockdims = blockdims_from_blockshape(x.shape, blockshape)
    798     name = name or next(names)
--> 799     dask = merge({name: x}, getem(name, blockdims=blockdims))
    800     return Array(dask, name, blockdims=blockdims, dtype=x.dtype)
    801 

/Users/shoyer/dev/dask/dask/array/core.pyc in getem(arr, blockdims, blockshape, shape)
     46         blockdims = blockdims_from_blockshape(shape, blockshape)
     47 
---> 48     cumdims = [list(accumulate(add, (0,) + bds[:-1])) for bds in blockdims]
     49     keys = list(product([arr], *[range(len(bds)) for bds in blockdims]))
     50 

TypeError: 'int' object has no attribute '__getitem__'
```

There might be something to be said for switching the order of these arguments -- blockshape is much more convenient for interactive use.

**Comment by shoyer** [comment]
When I first tried `dask.array`, I immediately tripped over the blockshape/blockdims distinction. It's pretty obvious after a bit of inspection, but blockshape is definitely the more intuitive way to control chunk sizes. For example, it's the only option provided by h5py or netCDF4 for specifying chunk sizes, though they give it different names (`chunks` or `chunksizes`).

Frankly, it's also a bit of a pain to wrap both arguments in xray and when working with dask I've routinely accidentally used a blockshape when I should be passing blockdims. So I'm pretty strongly in favor of Matthew's proposal 1, and also combining these arguments under one of these names.

**Comment by shoyer** [comment]
also fixed by https://github.com/ContinuumIO/dask/pull/160
