### ISSUE TITLE
da.constant ignores the dtype argument

### ISSUE THREAD

**Issue by shoyer** [ContinuumIO/dask#128]
```
In [1]: import dask.array as da

In [2]: da.constant(1.0, shape=(10, 10), blockshape=(10, 10), dtype=float)
Out[2]: dask.array<constant-1, shape=(10, 10), blockdims=((10,), (10,)), dtype=None>
```
It's much easier to notice these things with the new repr :)

Also, perhaps we should simply use [`np.full`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.full.html) instead? That function was added in numpy 1.8...

**Comment by mrocklin** [comment]
Full looks like a winner.  I'd actually like to rapidly deprecate constant, replacing it will full.  Any objections?

**Comment by shoyer** [comment]
I haven't used `constant` in xray at all, so it's good to go from my perspective.

On a somewhat related note, given that dask arrays are immutable (right?), it could be nice to use `broadcast_to` to avoid actually allocating constant arrays in memory (like the trick I used for [insert](https://github.com/ContinuumIO/dask/pull/130)).

Or even better, we might even create a single key in the dask to which all blocks (with the same size) point simultaneously.
