### ISSUE TITLE
List indexing followed by newaxis indexing fails

### ISSUE THREAD

**Issue by shoyer** [ContinuumIO/dask#133]
```python
import dask
import dask.array as da

da.set_options(get=dask.get)
x = da.zeros(shape=(5, 5), blockshape=(3, 3))
x[[0, 1]][None].compute()
```
```
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

I think I might need to actually write those futz tests for indexing :).

**Comment by mrocklin** [comment]
Hrm, what concerns me more is that two dask arrays with the same blockdims behave differently.  That breaks a decently strong dask.array principle.

**Comment by mrocklin** [comment]
```python
In [35]: x[[0, 1]][None].compute()
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

     60         if not args:
---> 61             val = func(*results)
     62             if len(stack) == 1:

ipdb> print func
<built-in function getitem>
ipdb> print results
[array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]]), (None, (0, 1, slice(0, None, 1)), slice(0, None, None))]
```

Hrm, something isn't right with the slices there.  It looks like this is a problem with the fuse_slice optimization.  It's joining nested getitems in a case where it shouldn't.  Turning it off fixes the error.  I'll take a look at this tomorrow.

**Comment by mrocklin** [comment]
This is fixed (I think) in https://github.com/ContinuumIO/dask/pull/134

Futz testing still appreciated.
