### ISSUE TITLE
Should dask.array coerce eagerly evaluated input to numpy.ndarray?

### ISSUE THREAD

**Issue by shoyer** [ContinuumIO/dask#139]
This is a generalization of the specific issue in https://github.com/ContinuumIO/dask/issues/105

For example, if `array.compute()` is called on dask array wrapping an already lazy array, it can return the lazy array instead of computing the values.

Likewise, we run into trouble if we try to do computation on lazy arrays that don't support computation.

There are two possible solutions here. Either we can declare that:

1. All arrays passed to `da.from_array` should produce a "computable" array when indexed. This can be any arbitrary array object as long as it satisfies the required API (e.g., it could be a numpy MaskedArray or astropy.quantity), or...
2. Dask should always coerce the result of indexing an array passed to `from_array` to an numpy array, either with (a)  `np.asanyarray` or (b) `np.asarray`.

Option 2(b) will probably lead to the less unexpected behavior, but it will require a bit more work and be slightly less flexible. For example, it precludes cleverness like using a lazy "virtual" array that implements shortcuts for arithmetic (e.g., by offloading work on a remote server/backend outside of dask).

**Comment by mrocklin** [comment]
My original intent was 2(b).  I'll implement this in the next bit if no comments.
