### ISSUE TITLE
Consider renaming "block" to "chunk"

### ISSUE THREAD

**Issue by shoyer** [ContinuumIO/dask#150]
Reasons why I like "chunk" better than "block":

1. It's the term used by HDF5 and netCDF4.
2. Both "chunk" and "rechunk" work as verbs. The verb "block" refers to stopping something. Hence I can call an xray method that coercing arrays to data arrays (either with `da.from_array` or `da.reblock`) `chunk_data`, but it would sound weird to call it `block_data`.
3. ~~Maybe: the argument `chunks=(100, 100)` (e.g., as used by h5py) seems a little less ambiguous to me than `blocks=(100, 100)`, which could refer to either the dimensions of each block or the total numbers of blocks.~~

I'll report back with the results of some informal usability tests on my co-workers.

**Comment by mrocklin** [comment]
I'm open to this.  Adhering to standards set out by hdf5 seem reasonable.  It's a bit of a pain to change things, but doable.

**Comment by shoyer** [comment]
In a highly non-scientific fashion, I polled n=3 of my co-workers. They agreed (not especially strongly) on my points 1 and 2; they did not agree on 3.

We could do this change coincidently with a fix for #124. I'm thinking of the following changes to the API, though this might be too extreme:

1. `da.Array.blockdims` -> `da.Array.chunks`
2. `da.reblock` -> `da.rechunk`? (this one doesn't sound so nice) Maybe `da.set_chunks`?
2. In `da.from_array` and `da.reblock` signatures: consolidate `blockdims`and `blockshape` into the single parameter `chunks`, which allows for either input.

**Comment by cowlicks** [comment]
Just to be clear. "chunks" in dask would be unrelated to "chunks" in odo? There is an [open PR](https://github.com/ContinuumIO/odo/pull/28) in odo for renaming chunks -> iterable. [Blaze](http://pandas.pydata.org/pandas-docs/version/0.15.2/io.html#io-chunking) uses the term. And so does [Pandas](http://pandas.pydata.org/pandas-docs/version/0.15.2/io.html#io-chunking)

It would be nice if this terminology were consistent across these projects since they are closely related.

**Comment by shoyer** [comment]
Actually, it's a pretty similar idea -- "chunking" refers to dividing a big file into medium sized pieces for consumption.

**Comment by mrocklin** [comment]
1. `da.Array.blockdims` -> `da.Array.chunks`  --  I'm ok with this
2. `da.reblock` -> `da.rechunk`? (this one doesn't sound so nice) Maybe `da.set_chunks`?  -- set_chunks sounds like a mutable operation to me.  I would opt for rechunk.
2. In `da.from_array` and `da.reblock` signatures: consolidate `blockdims`and `blockshape` into the single parameter `chunks`, which allows for either input.  --  I think that this is a good idea

Sorry to drag my feet on this.  A bunch of other things happened.  I can probably manage this sometime next week.

**Comment by shoyer** [comment]
`rechunk` sounds awkward to me, but is [already in use](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=hdf5+rechunk). So yes, let's do that.

No worries about feet dragging -- you were spreading the good word about xray + dask!

**Comment by shoyer** [comment]
Fixed by https://github.com/ContinuumIO/dask/pull/160
