### ISSUE TITLE
`dask.async` always computes the entire dask

### ISSUE THREAD

**Issue by ibab** [ContinuumIO/dask#153]
I'm confused that `dask.async` seems to compute the entire dask every time instead of only running the tasks necessary to create a key:
```
d = dict(x=(print, 'a'), y=(print, 'b'))
import dask.async
dask.async.get_sync(d, 'x')
```
This prints
```
b
a
```
Is this intended?
The `get` function from `dask.core` only executes the required tasks.

**Comment by mrocklin** [comment]
Usually we use `dask.optimize.cull` to remove the unnecessary tasks before execution.

**Comment by ibab** [comment]
`cull` works great, thanks!

I'd say it would make sense to cull the graph by default in `get_async`, to get its behavior in line with the simple `get`. Otherwise, the difference is a bit confusing when using dask for the first time.
Or is there a usecase where one needs to evaluate the entire graph?

**Comment by mrocklin** [comment]
> I'd say it would make sense to cull the graph by default in get_async

That might be reasonable to do.  This hasn't come up because no one has yet used the schedulers isolation (i.e. without using dask.array/dataframe/bag).  I'd be curious to hear what you're working on.

> Or is there a usecase where one needs to evaluate the entire graph?

Nothing comes to mind immediately.  Perhaps if someone wanted to execute the graph for the side effects and didn't care about results?

**Comment by ibab** [comment]
> I'd be curious to hear what you're working on

I've recently started building a data analysis framework for python: https://github.com/ibab/datapipe.
Basically, I'm trying to build something very similar to [luigi](https://github.com/spotify/luigi), but more suited to the workflow I need as a high energy physicist.

`dask` has been very helpful so far, as it allowed me to skip implementing all of the usual graph operations. Especially doing the asynchronous execution properly would have been a lot of work. :smile:

**Comment by mrocklin** [comment]
It's cool to see someone use just a piece of dask.  Hooray for modularity.
