### ISSUE TITLE
Default ThreadPool for dask.array

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#154]
Currently we spin up a separate ThreadPool for each `dask.array` computation.  This adds about 100ms overhead to every full computation (not every task.) This can add up for applications, like xray, that might manage operations on many small dask.arrays.

Do we want to have a single default `ThreadPool`?  Are there any costs to this?

**Comment by shoyer** [comment]
Threads use up about 8MB of memory each, according to [Effective Python](http://www.amazon.com/Effective-Python-Specific-Software-Development/dp/0134034287/ref=sr_1_1?ie=UTF8&qid=1429042387&sr=8-1&keywords=effective+python) (which I just read on an airplane and highly recommend!). These days, typical machines have ~1-4GB of memory per CPU, so IMHO allocating 1-2 threads/CPU would pretty much be rounding error and a really nice idea from a usability perspective.

OTOH, it's also pretty easy for applications like xray to create the global threadpool as a resource at import time, too.

We did get a complaint about this in pandas: https://github.com/pydata/pandas/issues/9394
