### ISSUE TITLE
pframe: allow string column index

### ISSUE THREAD

**Issue by ARF1** [ContinuumIO/dask#156]
I have been playing a bit with the new dask.dataframe which looks very promising. One problem I have encountered is that I cannot index on bcolz string columns. 

Attempting to do so results in the error "Object dtypes not supported, consider categoricals". Even if `categorize=True` is enabled.

As I understand this is related lack of pandas categorical indexes. While we are waiting for this, would it be possible to allow object indexes and only issue performance warnings?

**Comment by mrocklin** [comment]
@jreback has been kind enough to fast-track categorical index.  See https://github.com/pydata/pandas/pull/9741

Also, general disclaimer, dask.dataframe isn't quite ready for prime-time.  I'm unlikely to rush this.

**Comment by mrocklin** [comment]
I'd also be quite happy to hear about how you're using (or would like to use) dask.dataframe.  Driving use cases are most welcome here.

**Comment by mrocklin** [comment]
The categorical index PR was merged.  I'm going to close this.  Things should work if you run from pandas master or next time pandas is released.
