### ISSUE TITLE
Debugging problems with Microsoft PTVS

### ISSUE THREAD

**Issue by ARF1** [ContinuumIO/dask#157]
When using Microsoft Python Tools for Visual Studio, debugging is broken due to the PTVS limitation described in Microsoft/PTVS#17.

The problem lies in the exception types flowing through a variable in this type of code segments:
```
with ignoring(ImportError):
    import invalidImport
```

As I understand, if the following would be used, no problem would occur:
```
with ignoring_ImportError():
    import invalidImport
```

Maybe a solution to the PTVS bug could be suggested to the PTVS team that would resolve the issue without changing dask code?

**Comment by mrocklin** [comment]
`ignoring` (or rather, `ignored`) has actually been added to Python itself (https://hg.python.org/cpython/rev/406b47c64480) . This is probably something that should be fixed on the PTVS side.

That being said, if there is a particularly troublesome spot where this occurs frequently we could expand out to the try-except module.  Are there a few painful places where this comes up?

**Comment by ARF1** [comment]
Many thanks for the explanation: clearly PTVS has to deal with the issue since the idiom has become part of the stdlib.

In the few tests I have done so far, it only came up once for each invalid import. I am closing this for now. If it should become an annoyance I will come back to this issue.

**Comment by mrocklin** [comment]
Thanks.  Don't hesitate if this becomes a pain.  We can always revert to try-except.
