### ISSUE TITLE
Break apart or merge subprojects?

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#161]
Dask has a few different subprojects and a few different use cases.  How should we package and distribute these?

There are three main collections, each has dependencies and each has tiny subprojects

* `dask.array` - just numpy
* `dask.dataframe` - numpy, pandas, bcolz, as well as our internal pframe project
* `dask.bag` - not numpy, but definitely `dill` as well as our internal pbag project

All are valuable, yet there is probably some value to future bag users if they don't have to install bcolz (bag could be pure-python).  So some questions:

1.  Should we have separate `pip install dask-bag` records on conda/PyPI?  if so how does one do this?
2.  How should we handle the microprojects `pframe` and `pbag`?  Should these be merged into dask.dataframe and dask.bag respectively?  Should they live in separate repositories?

I'm pretty ignorant on packaging best practices

**Comment by shoyer** [comment]
`dask.array` users will also probably be annoyed to need to install bcolz. Note that I'm contemplating making dask a required dependency for some future of xray (not the next release).

One option would be to copy the IPython folks and use [`extras_require`](http://stackoverflow.com/questions/19096155/setuptools-and-pip-choice-of-minimal-and-complete-install) in setup.py to make it easy to install dask with optional dependencies. I don't think we need separate repos yet, although I could see a case for that, especially if/as the core + dask.array becomes much more stable than the other components.

**Comment by mrocklin** [comment]
Do you have thoughts on how we should handle the side projects like [`pframe`](https://github.com/ContinuumIO/dask/tree/master/pframe)?

**Comment by shoyer** [comment]
Not particularly, to be honest :). I think it's fine to keep them in dask,
as long as they aren't unduly influencing release cycles.
