### ISSUE TITLE
Setup conda recipe and binstar.yml

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#175]
We should probably have a conda recipe in the dask library itself.  We would also like to set this up to build under the blaze channel on binstar-build so that conda users can get bleeding-edge builds.  The Blaze/datashape/odo projects can serve as a decent model here.

One issue is that the `chest` dependency isn't currently available by conda/anaconda.  We either need to get https://github.com/ContinuumIO/anaconda/pull/160 merged, create packages ourselves in a similar fashion, or just wrap those packages into the dask package.

**Comment by cowlicks** [comment]
I can see chest and heapdict in the conda defaults channel now. https://github.com/ContinuumIO/anaconda/tree/master/packages/chest-0.2.2

**Comment by cowlicks** [comment]
closed by #192
