### ISSUE TITLE
Deploy dask.distributed setup with ipython.parallel view

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#199]
Given an IPython parallel Client or view (not sure which is best) it would be nice to spin up a dask.distributed Scheduler/Worker system.  This lets us hijack some of the work the Jupyter team has done integrating with various job management systems (pbs, ssh, etc..) and their surrounding infrastructure.

This should be relatively straightforward with a [moderate understanding of dask.distributed](http://dask.pydata.org/en/latest/distributed.html#setup) and serves as a good opportunity to get ones feet wet (it also puts a second pair of eyes on this module.)

We want to set up one `Scheduler` and then a bunch of `Worker`s that all know where the scheduler lives.  Finally we want to return a `dask.distributed.Client` to the user pointing to that same scheduler.

Example
------ 

```python
>>> from IPython.parallel import Client  # note that this is a different Client object
>>> view = Client(...)[:]

>>> from dask.distributed import from_ipython_parallel  # or some better name
>>> c = from_ipython_parallel(view)

>>> c.get({'a': 1, 'b': (lambda x: x + 1, 'a'}, 'b')
2
```

It would also be great to get feedback (or just changes) to improve the experience of interacting with dask.distributed.  Presumably there are also bugs lying around.

**Comment by cowlicks** [comment]
will be closed by #208
