### ISSUE TITLE
Travis.ci tests on 2.7 always pass

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#210]
I must have written down this line incorrectly.  The goal was to only test doctests and upload coverage results on 2.7

**Comment by cowlicks** [comment]
I don't understand what your saying. There is a line somewhere forcing these tests to pass?

**Comment by mrocklin** [comment]
The tests fail but we still get a green check.  [this line](https://github.com/ContinuumIO/dask/blob/master/.travis.yml#L29) is flawed

**Comment by cowlicks** [comment]
closed by #295
