### ISSUE TITLE
Bag.from_url

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#242]
Similar to #241 we might want to construct bags from resources found on the web.  The following lines from githubarchive.org show a possible api using unix-style options with ranges.

* Activity for 1/1/2015 @ 3PM UTC	`wget http://data.githubarchive.org/2015-01-01-15.json.gz`
* Activity for 1/1/2015	`wget http://data.githubarchive.org/2015-01-01-{0..23}.json.gz`
* Activity for all of January 2015	`wget http://data.githubarchive.org/2015-01-{01..30}-{0..23}.json.gz`

Is there a simple python way to duplicate this behavior?  Is `urllib2.urlopen` the best way to pull down data?

**Comment by shoyer** [comment]
This is also something we do all the time. A tricky aspect of this is that it is quick easy to hit limits when querying URLs (especially when done concurrently) -- you really need some retry/backoff logic. Also, it's quite often handy to be able to cache results on disk locally.

**Comment by mrocklin** [comment]
I wonder if we can handle retry/backoff logic outside of the dask graph.  Presumably this could be wrapped up in some robust `urlopen` function.  Under what cases does urlopen fail?

**Comment by cowlicks** [comment]
Wouldn't the urllib or requests handle the retrying? http://stackoverflow.com/a/15431343

**Comment by cowlicks** [comment]
Should we check if each URL exists before making the bag? We could do this by requesting a HEAD from each URL.

**Comment by mrocklin** [comment]
I would do the simplest thing until a practical problem or user guides us to make a change.
