### ISSUE TITLE
rec_concatenate slows down ghosting computations

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#243]
In [this notebook](http://nbviewer.ipython.org/gist/mrocklin/dc7fd426a6e405fef275) we find that concatentation within dask.array.ghost is a bottleneck.  Currently this depends on `rec_concatenate` which makes several recursive calls to `numpy.concatenate`; this is wasteful. 

Instead it would be nice to allocate one target array and then insert all of the source arrays into the proper place

```python
result = np.empty(...)  # allocate once

for location, x in ... : # some recursive looping, possibly with itertools.product
    result[*location] = x  # insert each array individually
```

It would be interesting to see how much this can improve performance.  It would also be good to profile the application in the above notebook to establish that the lower bound is good enough to warrant this effort.

cc @cowlicks @ahmadia @ketch

**Comment by mrocklin** [comment]
It could also be that a simple call to `np.array` has this behavior.  A simple replacement of `rec_concatenate` with `np.array` in [`ghost_internal`](https://github.com/ContinuumIO/dask/blob/master/dask/array/ghost.py#L112) breaks tests

**Comment by mrocklin** [comment]
cc @shoyer in case he has a good solution to this.

**Comment by shoyer** [comment]
I agree with your diagnosis. In my experience, repeated allocation with nested concatenation can indeed be a bottleneck. I don't have a quick solution, though -- I don't entirely understand what you're doing with rec_concatenate :).

**Comment by cowlicks** [comment]
It seemed like black-magic to me too. I'd like to better understand what is going on here so I'll take a look.

**Comment by ketch** [comment]
+1 I would love to try this out if it's not too hard for you to implement.  Real kernels of interest are more expensive than the heat FD kernel, so they will offset the overhead to a greater degree.

**Comment by cowlicks** [comment]
@ketch This is not high priority for me, so go for it if you are interested.

**Comment by mrocklin** [comment]
I'll give this a shot when I have a moment.  Probably early next week.
