### ISSUE TITLE
dask.bag.from_filenames fails with distirbuted scheduler when workers and client have different paths

### ISSUE THREAD

**Issue by cowlicks** [ContinuumIO/dask#250]

**Comment by mrocklin** [comment]
I'm not sure that we should try to fix this other than by informative error messaging.

**Comment by cowlicks** [comment]
@mrocklin why not? The fix seemed pretty easy. See #251

**Comment by mrocklin** [comment]
Ah, I see, they live on the same file system.  Yes, abspath sounds like a
good idea.

I was pessimistic about the case when they had different file systems.

**Comment by mrocklin** [comment]
There should be some quote about "premature pessimism is the root of all ____" for some ___
