### ISSUE TITLE
Support for randomized partitions of datasets

### ISSUE THREAD

**Issue by diehl** [ContinuumIO/dask#252]
I'd love to see future capability that allows one to perform a randomized partition of a dataset and follow-on computation on the partitions. This is critical for simple hold-out tests and cross-validation to assess the generalization performance of models resulting from machine learning.

**Comment by mrocklin** [comment]
What are your thoughts on reading through the data twice?  How performance critical is this operation in your workflow?

Do you need exactly a certain split or are you ok with a slightly uneven split?  E.g. you ask for 80/20 but you get 81/79.

Is there ever a case where you care about partitioning into more than two sets?

**Comment by diehl** [comment]
It'd be nice to avoid that but I can imagine this could be problematic without explicitly writing the partitioned datasets to disk. If you generate the partition index prior to streaming through the data, is it complicated to have multiple computational pipelines for the different partitions?

Regarding performance, it really all depends on the application. Nothing I'm thinking about is actually real-time currently but I'd prefer as much performance as possible. Otherwise there's really no reason not to load the data on a huge EC2 instance and load it all into RAM. I'm specifically thinking about using Blaze in the context of medium data problems. 

Regarding the partition, 80/20 might not always be exactly possible so no worries there. I just want to know exactly how many examples are in each partition when I'm computing test statistics. 

If I'm operating with so much data that I can't load it all into memory, it's very unlikely I'd be thinking about doing a k-fold cross-validation. More likely is partitioning the data three ways actually into training data, validation data and test data.

**Comment by mrocklin** [comment]
>  If you generate the partition index prior to streaming through the data,

What I have in mind is using a hashing function rather than an index.  

> is it complicated to have multiple computational pipelines for the different partitions?

It isn't complicated.  We do this thing all the time in dask.array for more complex operations.  It becomes a bit more complex in dask.dataframe due to GIL and serialization issues if you try to parallelize things with multiprocessing.  My question about how much you care was just a question, not a statement of "this is really hard."  It sounds like your answer is "I care a non-trivial amount."

**Comment by diehl** [comment]
Splitting at least three ways for training, validation and test for medium/big data is the minimum requirement. One brings k-fold cross-validation to bear when data is constrained. Hard to imagine that being necessary when one has more data than can fit in RAM. Hope that helps!

**Comment by shoyer** [comment]
@diehl are you datasets tabular or array based? I'm guessing tabular, because for out of core arrays (with N > 1) doing the split is pretty straightforward using the normal numpy/scitkit-learn methods.

**Comment by diehl** [comment]
@shoyer how do you define the distinction between array and tabular?

**Comment by shoyer** [comment]
@diehl If you stored your data in a matrix, what would be the shape of that matrix? If the matrix has shape `(M, N)` and `M >> N`, then I would call the data tabular. This is a much harder problem than if `M ~ N` because in the later case you can easily store vectors of length `M`.

**Comment by diehl** [comment]
@shoyer I would definitely be using tabular data with Blaze. Odds are if M ~ N, then the data will likely fit into RAM.

**Comment by mrocklin** [comment]
This is perhaps resolved in #276
