### ISSUE TITLE
dot_graph does not work in stable version

### ISSUE THREAD

**Issue by koldunovn** [ContinuumIO/dask#255]
I try to generate visual graphs as [described in documentation](http://dask.pydata.org/en/latest/inspect.html), but get:
```'module' object has no attribute 'to_pydot'```

The graphviz is installed with homebrew. Dask is installed from conda (latest stable release):
```
In [15]: dask.__version__

Out[15]: '0.5.0'
```

The code and traceback are below (I had to replace `blockshape` with `chunks`, otherwise it did not create task graph):

``` python
In [1]: 
import dask.array as da
from dask.dot import dot_graph
In [2]:

x = da.ones((5, 15), chunks=(5, 5))
In [5]:

d = (x + 1).dask
In [6]:

dot_graph(d)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-c797e633866d> in <module>()
----> 1 dot_graph(d)

/Users/koldunov/miniconda/lib/python2.7/site-packages/dask/dot.pyc in dot_graph(d, filename, **kwargs)
     73 def dot_graph(d, filename='mydask', **kwargs):
     74     dg = to_networkx(d, **kwargs)
---> 75     write_networkx_to_dot(dg, filename=filename)
     76 
     77 

/Users/koldunov/miniconda/lib/python2.7/site-packages/dask/dot.pyc in write_networkx_to_dot(dg, filename)
     61 def write_networkx_to_dot(dg, filename='mydask'):
     62     import os
---> 63     p = nx.to_pydot(dg)
     64     p.set_rankdir('BT')
     65     with open(filename + '.dot', 'w') as f:

AttributeError: 'module' object has no attribute 'to_pydot'
```

**Comment by mrocklin** [comment]
Hrm, perhaps one also needs to install the pydot library

    pip install pydot

We haven't included these in the dependencies because the visualize stuff is useful but not essential.  If this fixes the problem let me know and I'll improve the error message to direct future users to the solution.

**Comment by koldunovn** [comment]
Yes, that fixes  the problem, thanks a lot! I am not sure if you also have to replace `blockshape` with `chunks` in documentation, otherwise the example did not work.

**Comment by mrocklin** [comment]
Where did you find `blockshape`.  Yes, these should all be replaced with `chunks`.

**Comment by mrocklin** [comment]
Ah, I see that you referred to the link in the docs.  Fixing.

**Comment by koldunovn** [comment]
Well strangely it worked only once and now I am getting 
```
Couldn't import dot_parser, loading of dot files will not be possible.
```

**Comment by mrocklin** [comment]
I get that same issue.  I suspect something is wrong upstream.
