### ISSUE TITLE
Block-wise implementation of randomized PCA

### ISSUE THREAD

**Issue by alimanfoo** [ContinuumIO/dask#265]
I work with large arrays of genotype data of shape (n_variants, n_samples, 2), where n_variants is ~20000000 and n_samples is currently ~1000. These data are derived from next-generation sequencing of Anopheles mosquitoes, which we are studying because of their role in malaria transmission in Africa. A typical analysis we perform is to first reduce this to a 2D array of shape (n_variants, n_samples) then perform a principal components analysis of variants (features) against samples (observations), to look for patterns in the genetic relatedness between mosquito samples. 

I have tried both conventional SVD via numpy.linalg and the randomized PCA implementation in scikit-learn. The randomized implementation is roughly an order of magnitude faster and uses about half the memory. Given the large number of features we have to deal with, both reductions in memory footprint and increases in speed are very valuable, enabling exploratory analysis of large datasets within an interactive session.

Today we tried the dask block-wise SVD implementation which seems very promising because of the much-reduced memory requirements. If dask had a blocked implementation of randomized SVD that would be even better, making principal components analysis of these data very quick and scalable.

**Comment by alimanfoo** [comment]
Btw code I currently use for both conventional and randomized PCA can be accessed from [here](http://scikit-allel.readthedocs.org/en/v0.14.0/stats/decomposition.html) via the "source" links.

**Comment by mrocklin** [comment]
@marianotepper thoughts on this?  I know that you've spoken about randomized out-of-core SVD in the past.  Is this something that is reasonable to put into `dask.array.linalg`?

**Comment by shoyer** [comment]
cc @ToddSmall who has made similar observations to me.

**Comment by marianotepper** [comment]
I have been planning to add this feature for quite some time now.
I have code for doing exactly this that is 95% ready. Basically, the randomized part is done, I just need to add the SVD computation and we would be good to go. I will make some time on Saturday to port the code and put everything together. Hopefully by Monday, everything will be already in place and working!

**Comment by marianotepper** [comment]
Here's a first version of a randomized/compressed SVD implementation:
https://github.com/marianotepper/dask/blob/master/dask/array/linalg.py#L169-240

**Comment by mrocklin** [comment]
Cool.  I have a few questions, but I'll wait for the PR so that I can put them inline.

Generally how is the performance?  This is the first time I've seen the power method used on a dask.array.  Presumably for the tall-and-skinny case the graphs don't get *too weird* here but still, things might get interesting.

**Comment by marianotepper** [comment]
The general method is very fast for really large arrays. It only needs two
passes over the input matrix to perform its SVD. Moreover, using the
subsampled Fourier or Hadamard transforms, instead of a Gaussian random
matrix, would significantly improve the method's performance.

FYI, this algorithm does not require the input matrix to be tall and skinny.

**Comment by mrocklin** [comment]
Approximate OOC SVD has been merged.  Closing this.

**Comment by shoyer** [comment]
Well done @marianotepper ! Looking forward to giving this a spin.
