### ISSUE TITLE
Unexpected b.str.split().take(3) not printing the three items in list(b.str.split())

### ISSUE THREAD

**Issue by chdoig** [ContinuumIO/dask#268]
I was testing out a simple example from the tests (test_str_empty_split in test_bag.py): (https://github.com/ContinuumIO/dask/blob/a16f8387791c5f376e87b7cacc6ef687e8652f56/dask/bag/tests/test_bag.py#L395-L400)

and got an unexpected result:

```python
In [1]: import dask.bag as db

In [2]: b = db.from_sequence([u'Alice Smith', u'Bob Jones', 'Charlie Smith'],
   ...:                      npartitions=2)

In [3]: b.str.split().take(3)
Out[3]: ([u'Alice', u'Smith'], [u'Bob', u'Jones'])

In [4]: list(b.str.split())
Out[4]: [[u'Alice', u'Smith'], [u'Bob', u'Jones'], ['Charlie', 'Smith']]
```

Why is 'Charlie Smith' in the list but not in take(10)?

**Comment by eriknw** [comment]
According to the docstring, `take` only gets from the first partition.  "Charlie Smith" is part of the second partition.

**Comment by chdoig** [comment]
I should have read that. I thought it had something to do with "Charlie Smith" being a str and not unicode.

**Comment by chdoig** [comment]
Maybe take() should be independent of the number of partitions you give, and check if items in first partition are less than the argument passed to take, and then append from the next if it's in fact less? Or maybe that's too much overhead for this corner-case.

In the same example, if I don't pass partitions and do take(3), I actually just get one item. So, the naive user, who just uses the default number of partitions, might be surprised or confused by some of the results.

**Comment by mrocklin** [comment]
The behavior that you suggest would be less surprising.  With current dask architecture it would require one of the following:

1.  We would have know the number of elements in each partition at graph construction time
2.  We would have to compute all of the partitions

Sadly neither is true.  Closing for now.  Without a major reinvention this isn't likely to happen.
