### ISSUE TITLE
Reinvent ocean slider demo

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#277]
Here is an old demo from Continuum showing off Bokeh and NumPy

http://162.243.42.178:9000/v5.0/bokeh/ocean/

This demo lets the user slice through a large HDF5 file on disk and presents various views onto the screen.  Now that dask.array is around and that high-level bokeh is more advanced it might be useful to refresh this demo, perhaps using a pure-python bokeh solution (I suspect that the old demo had plenty of custom javascript) and finding more computation to do with dask.array.  We could consider zooming, using `da.coarsen`, reducing 2d slices down to 1d line plots, etc..

This might be a good task for someone getting their feet wet with Continuum tools; in particular @jcrist might find it a valuable case study to actually use dask.array and to get to know Bokeh.  We might ask @cowlicks and @chdoig to answer questions about dask.array and Bokeh respectively.

I believe that @hhuuggoo knows where the dataset lives.  If it's hard to find then we could find something else (we have a few large arrays lying around.)

**Comment by mrocklin** [comment]
If we get this working then it might also be a good driving use case to develop caching policies and use `dask.store`, which might be a fun academic problem.

**Comment by mrocklin** [comment]
Hugo mentioned that the data was derived from [this dataset](ftp://ftp.cdc.noaa.gov/Datasets/noaa.oisst.v2.highres).  One could probably operate on this data much in the same was as is done in [this blogpost](http://matthewrocklin.com/blog/work/2015/02/13/Towards-OOC-Slicing-and-Stacking/)

**Comment by chdoig** [comment]
The old code of the ocean demo is here: https://github.com/bokeh/bokeh/tree/scipydemo2014/bokeh. Relevant files:
- ocean.py: https://github.com/bokeh/bokeh/blob/scipydemo2014/scripts/ocean.py
- volumeslicer widget: https://github.com/bokeh/bokeh/blob/scipydemo2014/bokeh/volumeslicer/objects.py

Bokeh's code base has changed a lot since then, so it might not be really useful after all, but just so that we have a reference.

**Comment by jcrist** [comment]
With the ocean slider demo that @mrocklin and @bryevdv worked up before SciPy, this (potentially) could be closed. Unless we wanted a different kind of demo using the data stored locally on disk.
