### ISSUE TITLE
linalg.tsqr not working in python 2.7

### ISSUE THREAD

**Issue by marianotepper** [ContinuumIO/dask#279]
I see that there were some changes in the inner structure of dask arrays since I coded the linalg module. One of them is the use of slice to create dask dicts. However, when I try to run the tests I get the error "TypeError: unhashable type" in lines 92 to 94 in linalg.

I believe that this is due to the slice class being non-hashable. Am I correct?

**Comment by mrocklin** [comment]
If you give me a failing example I'll be happy to track this down.  Things work for me in 2.7 (this is my normal development language).  I can't think of any changes that would affect dask.array.linalg off the top of my head.

**Comment by mrocklin** [comment]
I would not expect a hashability in those lines.  

```python
    dsk_q_st2 = dict(((name_q_st2,) + (i, 0),
                      (operator.getitem, (name_q_st2_aux, 0, 0), b))
                     for i, b in enumerate(block_slices))
```

Dicts only care about the hashability of keys which in this case is just `(name_q_st2,), + (i, 0)` which seems pretty harmless.

**Comment by marianotepper** [comment]
Sorry, my bad. Something weird I did when I rebased my fork. Thanks!
