### ISSUE TITLE
Turn on doctests in Travis-CI

### ISSUE THREAD

**Issue by cowlicks** [ContinuumIO/dask#283]
While fixing this #210 could also get fixed.

**Comment by mrocklin** [comment]
Many of our doctests are python version specific.  The solution so far has been to only doctest in 2.7.  I did this poorly, hence #210 .

**Comment by cowlicks** [comment]
Doctests are running on travis-ci with python 2.7. To see this look at a travis build and compare the number of tests collected between 2.7 and another build. [Here](https://travis-ci.org/ContinuumIO/dask/jobs/66425725) and [here](https://travis-ci.org/ContinuumIO/dask/jobs/66425724) for example.

Closing.

**Comment by cowlicks** [comment]
closed by #295
