### ISSUE TITLE
Add da.diag 

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#285]
Today I needed a dask.array equivalent for `np.diag`, in particular for the 1d to 2d case

```python
In [1]: import numpy as np

In [2]: np.diag([1, 2, 3])
Out[2]: 
array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])
```

Creating `da.diag` might be a good starter problem for @jcrist .  This would take a 1d dask Array object (with metadata like `.chunks` and `.dtype`), create a new dask graph with diagonal blocks on the diagonal and zero blocks elsewhere, and then create a new Array object with new `.chunks` (same `.dtype`) and a new graph caused by merging together the old graph and the new bit for the diag call.

**Comment by mrocklin** [comment]
This doc might be of use: http://dask.readthedocs.org/en/latest/array-design.html

**Comment by jcrist** [comment]
Would there be a use case ever for passing in a non `dask.Array` for the 1d sequence?

**Comment by mrocklin** [comment]
I'd skip it for now
