### ISSUE TITLE
Dask take fails with error in __bool__

### ISSUE THREAD

**Issue by HolgerPeters** [ContinuumIO/dask#289]
I have an issue with dask's implementation of `take`. I expect it to work as numpy's `take`, but it fails to compute. See the following snippet for an example:

```python
def test_dask_take():
    x = np.arange(10.0, 0, -1)
    choices = np.asarray([0, 0, 1, 1, 2, 2, 1, 1, 0, 0])
    res = x.take(choices)
    np.testing.assert_allclose([10., 10., 9., 9., 8., 8., 9., 9., 10., 10.], res)

    x_da = da.from_array(x, chunks=(x.shape[0]))
    choices_da = da.from_array(choices, chunks=(x.shape[0]))
    res2 = da.take(x_da, choices_da, axis=0).compute()  # <-- fails

    np.testing.assert_allclose(res, res2)
```
The traceback from py.test for this failure:

```
    ================================== FAILURES ===================================
    _______________________________ test_dask_take ________________________________

        def test_dask_take():
            x = np.arange(10.0, 0, -1)
            choices = np.asarray([0, 0, 1, 1, 2, 2, 1, 1, 0, 0])
            res = x.take(choices)
            np.testing.assert_allclose([10., 10., 9., 9., 8., 8., 9., 9., 10., 10.]
    , res)

            x_da = da.from_array(x, chunks=(x.shape[0]))
            choices_da = da.from_array(choices, chunks=(x.shape[0]))
    >       res2 = da.take(x_da, choices_da, axis=0).compute()

    test_dask.py:202:
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    ../dask/dask/array/core.py:1301: in take
        return a[(slice(None),) * axis + (indices,)]
    ../dask/dask/array/core.py:750: in __getitem__
        dsk, chunks = slice_array(out, self.name, self.chunks, index)
    ../dask/dask/array/slicing.py:100: in slice_array
        if all(index == slice(None, None, None) for index in index):
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    self = dask.array<x_4, shape=(10,), chunks=((10,)), dtype=bool>

        def __bool__(self):
    >       return bool(self.compute())
    E       ValueError: The truth value of an array with more than one element is a
    mbiguous. Use a.any() or a.all()

    ../dask/dask/array/core.py:722: ValueError
```

**Comment by mrocklin** [comment]
Dask.array.take currently expects a list or numpy array for the choices argument, not another dask.array.   We can index an out-of-core array with an in-core array, but not an out-of-core array with another out-of-core array.

It is hard to do this with another dask array because we are unable to look at the values of the choices dask.array to determine which input blocks affect which output blocks.

So this would work 

```python
>>> da.take(x_da, choices, axis=0).compute()
array([ 10.,  10.,   9.,   9.,   8.,   8.,   9.,   9.,  10.,  10.])
```

But this is actually a fairly hard problem to do generally:

```python
>>> da.take(x_da, choices_da, axis=0).compute()
```

This page on [dask.array's limitations](http://dask.readthedocs.org/en/latest/array-overview.html#limitations) might be a good read.

It could be that what you want to do is achievable through other means.  Why were you using `da.take`?

**Comment by HolgerPeters** [comment]
Agreed.

`da.take` with two dask arrays would be complex. However, I think that `da.take` could support a second case. Think of selecting lots of `choices` from a small `numpy.ndarray` `x`:

```python
>>> da.take(x, choices_da, axis=0).compute()
```

A small numpy array `x` can be held available, when evaluating choices on every chunk of `choices_da`. I.e.  `da.take(DA, NP)` is about taking a few samples from a big array, whereas `da.take(NP, DA)` is about choosing lots of values from a small sample.

**Comment by mrocklin** [comment]
Yes, I agree that that case is probably possible.  

Is this something you are actively trying to use or something that you've noted is possible (I'm trying to arrange this in my list of priorities.)

**Comment by HolgerPeters** [comment]
This is something I am actively trying to use, not just an observation along the way.
