### ISSUE TITLE
Improve Chest 

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#3]
Sometimes we need a cache that spills to disk.  

```Python
>>> from chest import Chest
>>> cache = Chest()
>>> dsk = ...
>>> dask.threaded.get(dsk, keys, cache=cache)
```

My current solution to this is [Chest](https://github.com/mrocklin/chest) an object that satisfies the `MutableMapping` interface that spills large contents to disk as pickle files.  When using this in production it worked, but not great.  We need something better.

One solution would be to improve chest.  A first step there would be to build a dask-like workflow to test chest and see what's falling down.  Is it concurrency, the lack of an LRU mechanism, the `O(n)` things we do on each spill to disk?

Another solution would be to look around and find something better, possibly [shove](https://pypi.python.org/pypi/shove/0.5.6) or something else in the ecosystem (or something new altogether.)

On disk caching will probably be necessary.

**Comment by wrobstory** [comment]
A question: how constrained can Chest's API be in terms of types? 

I ask because I think it would be interesting/fun/useful to implement either Thrift or Protobuf (or maybe we could try both and benchmark them) as a backend for Chest and be able to avoid pickle, because it's pickle. 

Another thought: If we *only* need mapping between keys and arrays, we might be able to create a custom serialization format around bcolz, and then we get all the benefits that entails.

Thoughts? This is a problem I'm interested in hacking on.

**Comment by mrocklin** [comment]
One could parametrize chest with strict key and value types and do some type checking.  Not sure if this should live outside or inside core `Chest` class.

Chest currently *can* be parametrized by `dump`/`load` functions so swapping in other protocols can be made to work that way.  

One reason that *I actually like pickle* is that it handles numpy and pandas very nicely (as long as you use `pickle.dump(..., protocol=2)`.  I'm pretty confident that this does almost no manipulation of the actual data bytes (though I'm sure that the metadata is entirely mangled).

Using BColz (or compression generally) also makes sense.  One thing to beware of is that bcolz often trades CPU for Memory bandwidth.  In the context of dask we may not have excess CPU to spare and minimally compressed may be better than in a normal, single-core case.

**Comment by mrocklin** [comment]
@wrobstory if you're at all interested in any of this I'd be thrilled.  

I think that efficient spill-to-disk data structures is a potentially very useful and relatively untapped development space.  I'd love to see someone revamp `chest` or even reinvent something newer and better (`chest` was a quick-and-dirty evening project).

**Comment by mrocklin** [comment]
I've added a naive LRU solution for chest in https://github.com/mrocklin/chest/commit/24210a5980a2c3691274db1432536921e9d868b5

**Comment by mrocklin** [comment]
And significantly reduced write costs by being less dumb in https://github.com/mrocklin/chest/commit/ba15e5ea561f18255f9db0885dd6626067cfa61d

**Comment by mrocklin** [comment]
And it's now threadsafe (maybe).  I'm going to close this for now.  Chest meets immediate requirements for use with numpy+dask things.  Blogpost forthcoming.
