### ISSUE TITLE
How to handle overflowing blocks?

### ISSUE THREAD

**Issue by jcrist** [ContinuumIO/dask#306]
How can we handle reductions on blocks that overflow, when the non-blocked calculation wouldn't? Example:

```python
>>> import numpy as np
>>> import dask.array as da
>>> x = np.arange(400, dtype='f4').reshape((20, 20))
>>> x.prod()
0.0    # Iterative, so 0.
>>> a = da.from_array(x, chunks=(7, 7))
>>> a.prod()
nan    # Some blocks overflow, resulting in inf, while one block is 0. 0 * inf = nan
```

We can't just say for `prod` that the reduction should have `0 * inf = 0`, as the `inf` might have resulted from an `inf` being in the array instead of an overflow.

I'm fairly certain this is too tricky to handle without the user's knowledge. However, we might be able to detect overflows and then raise a descriptive warning of the problem. `np.seterr` doesn't seem to allow for detecting overflows in builtin functions though, only in python-side operations.

**Comment by jcrist** [comment]
Upon further thought, I think the cases where this will happen in our blocked algorithms where it wouldn't happen in a non-blocked version are rare enough that we shouldn't worry. The above case is contrived, a simple reversal of the elements causes numpy to overflow to nan anyway. This can probably be closed.

**Comment by shoyer** [comment]
Agreed, I wouldn't worry about this.
