### ISSUE TITLE
Consistency in da.random

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#311]
Currently multiple calls to `da.random` functions don't produce consistent values

```python
In [1]: import dask.array as da

In [2]: x = da.random.random((2,), chunks=2)

In [3]: x.compute()
Out[3]: array([ 0.47001845,  0.54208932])

In [4]: x.compute()
Out[4]: array([ 0.23277611,  0.312902  ])
```

We should correct this, either by using `np.random.seed` in each block (perhaps with a lock around the pair of calls?) or with the RandomState API.

cc @shoyer @ogrisel

**Comment by ogrisel** [comment]
I would rather have an object oriented API to make it possible to seed the RNG for deterministic results akin to the `numpy.random.RandomState` API. E.g. to seed with the 42 integer which is arguably the best seed for random numbers:

```python
x = da.random.RandomState(42).normal(size=(2,), chunks=2 )
```

**Comment by mrocklin** [comment]
Can do.  I'll play with this on the plane today.
