### ISSUE TITLE
dask.dataframe.from_pandas

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#316]
Given a pandas dataframe we might want to create a dask.dataframe.  This would be for parallelism and for testing, not for out-of-core work.

We probably want to use `divisions`, which means that we'll need to ensure that the index is sorted.

We probably want to support both `pd.DataFrame`s and `pd.Series`'

This would be a good task for someone looking to familiarize themselves with dask.dataframe's design and would definitely help to improve our testing (where it's currently a bit of a pain to make a test `dd.DataFrame` object.)

```python
>>> df = # make pandas dataframe
>>> df2 = dd.from_pandas(df, npartitions=10)
```

**Comment by cpcloud** [comment]
Why not have separate `from_dataframe` and `from_series` methods?

**Comment by cpcloud** [comment]
I also like the idea of these being `classmethod`s rather than a global function.

**Comment by cpcloud** [comment]
Actually, upon implementing this I like the global function.

**Comment by cpcloud** [comment]
@jcrist What are your thoughts on a single `from_pandas` vs `from_dataframe` and `from_series`?

**Comment by jcrist** [comment]
I think it should be two functions. Keep it simple. Sometime in the future it may be nice to unite all of the `from_*` functions under some mega dispatcher (`daskify`?), but for now having each do one thing well sounds like the best plan.

**Comment by mrocklin** [comment]
`from_dataframe` and `from_series` conflict a little bit because there is now ambiguity between `pd.DataFrame`/`dd.DataFrame` and `pd.Series`/`dd.Series`.

We might have people trying to turn `dd.Series` objects into `dd.DataFrame` objects using `dd.from_series`.

**Comment by cpcloud** [comment]
In that case, what should `from_pandas` return?

**Comment by mrocklin** [comment]
I would suggest either a `dd.DataFrame` or a `dd.Series` depending on the type of the input.

**Comment by mrocklin** [comment]
In my mind this is a function where you give it a pandas thing and it gives you a dask.dataframe thing

**Comment by cpcloud** [comment]
cool, sounds good to me

**Comment by cpcloud** [comment]
Is the construction of a dask Series different from that of a DataFrame?

**Comment by mrocklin** [comment]
Very slightly.  Columns -> name
