### ISSUE TITLE
dask.dataframe.join

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#319]
DataFrame joins can take on a few forms based on how much we know about the left and right sides

* dask-pandas and pandas-dask: This is a trivial `map_blocks` operation
* dask-dask along index with known partitions:  In this case we can compute joins very efficiently by cross referencing the partitions and only joining those blocks where we know that there is some intersection
* dask-dask without known partitions:  When we join along a non-index column or when we don't know partitions, then we resort to a hash-join, probably using the shuffle mechanisms and `partd`

I plan to take this on (unless someone else feels adventurous.)

**Comment by cpcloud** [comment]
It'd be interesting to compare the second case with a join in postgres on indexed columns.

**Comment by mrocklin** [comment]
That would indeed be very interesting.  I'd also be interested in comparing against kdb partitioned tables.

**Comment by cpcloud** [comment]
You might be waiting a while on that one. You can't do inner joins with on-disk tables.

```
q).Q.qp[trade] // 1b means partitioned
1b
q).Q.ind[trade; til 3]
date       sym  time         price size stop cond ex
----------------------------------------------------
2013.05.01 AAPL 09:31:05.272 84.06 38   0    E    N
2013.05.01 AAPL 09:32:24.432 84.08 65   0    L    N
2013.05.01 AAPL 09:34:47.338 84.11 73   0    A    N
q).Q.qp[mas] // 0 means in memory
0
q)3 # mas
sym  name
------------------------------
AMD  "ADVANCED MICRO DEVICES"
AIG  "AMERICAN INTL GROUP INC"
AAPL "APPLE INC COM STK"
q)ej[`sym; trade; mas] // ej is inner join, first arg is column to join on
k){x,:();y[&#:'i],'(x_z)(!0),/i:(=x#z:0!z)x#y:0!y}
'splay
@
(+(,`sym)!,`sym$`AMD`AIG`AAPL`DELL`DOW`GOOG`HPQ`INTC`IBM`MSFT`ORCL`PEP`PRU`SB..
+(,`sym)!`trade
q.q))
```

**Comment by cpcloud** [comment]
That gobbledegook at the bottom is an error message

**Comment by mrocklin** [comment]
Fixed by https://github.com/ContinuumIO/dask/pull/360
