### ISSUE TITLE
Dask.array slow for parallel netCDF4 multi-file array operations

### ISSUE THREAD

**Issue by jcrist** [ContinuumIO/dask#326]
This came up when working on a dask demo using ocean data. Perhaps not a dask issue, but a good benchmark problem.

**The setup:**

I have 35 years of ocean data (from ftp://ftp.cdc.noaa.gov/Datasets/noaa.oisst.v2.highres/, just the `'sst.day.mean.*'` files) stored as netCDF4 files. Uncompressed, this is around 50 GB of data, but on disk is only ~15 GB. Each file is a year, broken into 365 arrays holding the daily mean temp every 1/4 degree. As a simple benchmark, I'm just trying to get the overall daily mean for each day. In numpy syntax, this would just be `data.mean(axis=(1,2))`, if the zeroth axis is along time.

**The issue:**

I composed this using `dask.array` to concatenate all the arrays together, chunking by day (matches netCDF chunks). I then used `map_blocks` to replace their sentinel value with `nan`, and then applied `da.nanmean(arr, axis=(1,2))` to it. Very composable, seemed good so far. The issue is that this was *slow*. Took `9:20`, around 1 min longer than it takes to read all data from disk *in serial*. 

Because the operation is embarrassingly parallel, we should be able to parallelize reads from the netCDF4 files (which is apparently supported), or just work on many files at the same time, with serial access to one file. Composing a dask doing this manually, and using the multiprocessing `get` function, I was able to get this down to `2:10` with 8 processes.

The issue is, I'd expect the threaded get to perform better than that. `np.mean` releases the gil, and supposedly `netCDF4` supports concurrent reads, but I wasn't seeing that. To verify that `netCDF4` wasn't reading concurrently in threading, I did this benchmark:

```
In [29]: data = netCDF4.Dataset('noaa.oisst.v2.highres/sst.day.mean.1982.v2.nc').variables['sst']

In [30]: from multiprocessing.pool import ThreadPool

In [31]: p = ThreadPool()

In [32]: iden = lambda a: a

In [33]: %time res = p.map(iden, data)
CPU times: user 13.7 s, sys: 928 ms, total: 14.6 s
Wall time: 14.6 s

In [34]: %time res = map(iden, data)
CPU times: user 13.7 s, sys: 859 ms, total: 14.5 s
Wall time: 14.5 s
```

Perhaps I'm mistaken about netCDF4 supporting concurrency in this manner (or the above benchmark is done poorly). Never worked with this file format before.

cc @shoyer for wisdom.

**Comment by shoyer** [comment]
netCDF4-python only releases the GIL for reads in the latest released version -- try updating?

Another option (if you know you're using netCDF4) is to try using [h5netcdf](https://github.com/shoyer/h5netcdf), which uses h5py instead of the netcdf4-C libraries under the hood.

**Comment by jcrist** [comment]
```
In [94]: netCDF4.__version__
Out[94]: '1.1.8'

In [95]: data.file_format
Out[95]: 'NETCDF4_CLASSIC'
```

I actually was just trying out h5netcdf. Iteration breaks on Variables (not sure if by design or , but using the underlying h5py Dataset I did the same benchmark as above - no change. I'm starting to wonder if that benchmark is even meaningful.

Using multiprocessing on a per file basis, I'm bound by the time it takes to process a single file in serial, which is dominated by the time it takes to read a file in. I'm not sure if there's a way to process a single file in parallel, or what kind of gains that would even get if it were possible. I may just have reached the i/o limit of my computer.

**Comment by jcrist** [comment]
Yeah, that benchmark was meaningless, `ThreadPool.map` partitions the dataset, which ends up loading it all into memory before running it. Doing this in a slightly different way:

```python
In [9]: f = lambda i: data[i].mean()

In [10]: %time res = map(f, range(365))
CPU times: user 15 s, sys: 1.06 s, total: 16 s
Wall time: 16 s

In [11]: %time res = p.map(f, range(365))
CPU times: user 14.9 s, sys: 1 s, total: 15.9 s
Wall time: 15.8 s
```

This seems to indicate that there's locking going on somewhere, so concurrent access to the same array isn't possible.

**Comment by mrocklin** [comment]
It seems odd to me that reading from a NetCDF file would be compute bound.  Perhaps the compression is a cause?

**Comment by shoyer** [comment]
> It seems odd to me that reading from a NetCDF file would be compute bound. Perhaps the compression is a cause?

Yes, netCDF4 files can compress individual chunks with zlib, which can be pretty slow to read.

 > Iteration breaks on Variables (not sure if by design or a bug)

Could you show an example?

**Comment by jcrist** [comment]
> Yes, netCDF4 files can compress individual chunks with zlib, which can be pretty slow to read.

That's only how the files are stored when they're pulled off the ftp site. Is there some other format that I could transform them to that would allow for faster access? Then intent is to demo some interactive data exploration, so fast read (no need to write) is very much desired.

> Could you show an example?

Filed an issue: https://github.com/shoyer/h5netcdf/issues/9

**Comment by mrocklin** [comment]
One could read them out and then store them into new files with a better
compression like lz4 or fastlz or perhaps no compression at all.

**Comment by shoyer** [comment]
Yep, would be pretty easy to read these files from netCDF4 and convert, e.g., to netCDF3 which doesn't have chunking or compression. With xray, that's just:
```python
with xray.open_dataset('file.nc') as ds:
    ds.to_netcdf('new-file.nc', format='netcdf3_classic')
```

**Comment by cpcloud** [comment]
I wonder if we should add xray into the odo graph as the default way to read netcdf* files. @shoyer thoughts?

**Comment by shoyer** [comment]
Matthew and I have discussed odo/xray. It doesn't really make sense since xray has such a  different data model than tabular datasets.

**Comment by cpcloud** [comment]
Odo isn't limited to tabular datasets. There just happen to be a ton of data that are in a tabular format :)

**Comment by mrocklin** [comment]
The XRay/NetCDF model links the dimensions of various arrays together.  Datashape loses this information.  The extent to which odo can handle netcdf is the extent to which it can handle HDF5.

Also, I haven't run into many people who have netcdf and are eager to switch to other formats.

**Comment by cpcloud** [comment]
Ok cool. Didn't mean to derail.

**Comment by mrocklin** [comment]
I suggest creating a dask.array object with all of the netcdf data, then calling the `to_hdf5` method.  This will probably dump all of the data into a single hdf5 file without compression.  One could then make a dask.array around that and compare performance.

**Comment by mrocklin** [comment]
One can also do this manually which would be a good thing to do to get a feel for the `h5py` and `netCDF4` libraries more directly.  I would just do the naive thing though unless you feel adventurous.

**Comment by jcrist** [comment]
I'm going to close this, as the parallel reads aren't a problem with dask, but with netCDF4/h5py.
