### ISSUE TITLE
Should rewrite rules traverse terms?

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#330]
I end up needing something like the following for the column-store optimizations in #325 

```python
In [1]: from dask.rewrite import RewriteRule, RuleSet

In [2]: rs = RuleSet(RewriteRule((1, 2), 3, ()))

In [3]: rs.rewrite((1, 2))
Out[3]: 3

In [4]: rs.rewrite((4, (1, 2)))  # I wish that this was (4, 3)
Out[4]: (4, (1, 2))
```

Should rulesets be willing to apply rewrite rules within terms and within lists?  Is this easy to accomplish with the existing system?

cc @jcrist

**Comment by jcrist** [comment]
Right now we only traverse tasks and lists. `(1, 2)` isn't a task (`1` isn't a callable), and the tuple isn't a list. We could go into tuples the same way we do lists though, the [spec](http://dask.pydata.org/en/latest/spec.html) didn't seem to indicate that this was allowed, so I didn't implement it. Easy fix, I can take care of this.

**Comment by mrocklin** [comment]
Hrm, good point.   Let me make sure that this is useful.

**Comment by mrocklin** [comment]
I have tasks like the following:

```python
 ('f-2', 221): (<function apply>,
  <function dask.dataframe.core.<lambda>>,
  (list,
   [(<function operator.getitem>,
     (<unbound method Castra.load_partition>,
      <castra.core.Castra at 0x7f694d413990>,
      '2014-12-11T08:00:54.000000000-0800--2014-12-12T08:59:59.000000000-0800',
      ['event', 'ip', 'software_branch', 'arch', 'platform', 'version']),
     'software_branch')])),
```

and a rewrite rule that looks like this

```python
        RewriteRule((getitem, (Castra.load_partition, '~c', '~part', '~cols1'),
                              '~cols2'),
                    (Castra.load_partition, '~c', '~part', '~cols2'),
                    ('~c', '~part', '~cols1', '~cols2')))
```

but the rule doesn't seem to trigger

**Comment by jcrist** [comment]
Hmmm, that looks like a bug. I'll take a look tomorrow.
