### ISSUE TITLE
Create a dask array from a function call

### ISSUE THREAD

**Issue by shoyer** [ContinuumIO/dask#344]
The other day, I needed to create a dask array by calling a function that creates a numpy array.  The way I did this is by constructing `LazyArray` objects and then calling `from_array` on them:
```python
class LazyArray(object):
    def __init__(self, func, shape, dtype):
        self.func = func
        self.shape = shape
        self.dtype = dtype

    def __getitem__(self, key):
        return self.func()[key]
```

I also considered just constructing the array directly using the `da.Array` constructor, but decided not to bother because I didn't want to worry about picking a unique name.

This seems likely to be a fairly common pattern, so it would be nice to have a convenience function. In my case, I had written a function to parse a strange file format, but I can also imagine this as a more general entry point for dask array (e.g., from computationally expensive functions). Perhaps `da.from_func(func, shape, dtype)`?

**Comment by mrocklin** [comment]
Is this the function you're looking for?

```python
def from_func(func, shape, dtype):
    name = next(names)
    dsk = {(name,) + (0,) * len(shape): (func,)}
    chunks = tuple((i,) for i in shape)
    return Array(dsk, name, chunks, dtype)
```

**Comment by shoyer** [comment]
Yes, that would do it.

**Comment by shoyer** [comment]
We might also want to support forwarding `**kwargs` on to the called function.
