### ISSUE TITLE
Async scheduler diagnostics

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#346]
The dask.async scheduler could support a callback during execution.  This could be useful for real-time visualization (as suggested by @jcrist) or for profiling (as suggested by @rhattersley) or for a variety of other unforeseen applications.

There is currently a kludgy `debug_counts` keyword argument to the single-machine scheduler that triggers a slow visualization step.  This hard-coded call to `visualize` should probably be replaced with a user-supplied callback.  

We would have to think about what inputs we provide to that callback, possibly the dask graph, state, newly finished task and newly started task.

This work could be enhanced by a couple of particular callbacks.  I would personally be interested in a function that recorded the start and end times of every task.  This could be coupled with a visualization of these task-durations, stacked up as necessary for the different threads/processes.

**Comment by rhattersley** [comment]
> a visualization of these task-durations, stacked up as necessary for the different threads/processes.

That's something we find [very useful](https://github.com/pelson/ipy_client_usage) when using IPython Parallel.
