### ISSUE TITLE
Profile visualization entirely grey when there are many tasks

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#397]
For graphs with very many tasks our pixel per box ratio may drop below 1, yielding an entirely gray visual result.  It looks fine once you zoom in but is confusing at first.  

I'm not sure what the right approach is here or if we should try to resolve this.  @bryevdv any thoughts on the right thing to do when the density of visual elements gets very high?

**Comment by jcrist** [comment]
I'm not sure if there's anything we can do for this. The user can always zoom in on the plot if they want more detail. A high level overview of parallelism would probably be covered by a different kind of plot.

At a high level, the data we have is (ignoring task data):
x = time
y = number of active workers at each timestep

Possible ways of plotting this include:
- A line graph (would be incredibly noisy)
- A smoothed line graph (sliding mean probably)
- A heatmap (hotter = more parallel)
- An area chart (x = time, width of area = how parallel)

I don't know if any of these are good ideas, or if they're even valuable. With many-many tasks you'd probably want to know

- How parallel is my graph overall (high level overview)
- Where in the graph am I losing parallelism (current plot, but zoomed in)

**Comment by mrocklin** [comment]
Closing for now.
