### ISSUE TITLE
dask.array should import its into

### ISSUE THREAD

**Issue by mfenner1** [ContinuumIO/dask#40]
This snippet fails:

```python
import dask.array as da
from blaze import Data, into
x = da.random.normal(10, 0.1, size=(10, 10), blockshape=(5, 5))
d = Data(x)  # this line bombs
```
but, this snippet works.
```python
import dask.array as da
from dask.array.into import into
from blaze import Data, into
x = da.random.normal(10, 0.1, size=(10, 10), blockshape=(5, 5))
d = Data(x)  # this line bombs
```

It looks like the only way dask.array's Array type gets registered to discovery is when dask/array/into.py is executed.  But, it is not imported in dask/array/\_\_init\_\_.py.

Thus, I think we should:
```diff
--- __init__.py	2015-02-21 08:25:20.000000000 -0500
+++ __init__-updated.py	2015-02-21 10:43:51.000000000 -0500
@@ -8,3 +8,4 @@
 from .reductions import (sum, mean, std, var, any, all, min, max, vnorm)
 from . import random, linalg
 from .wrap import ones, zeros, empty
+from . import into
```

**Comment by mrocklin** [comment]
I'd like to keep `dask.array` lightweight and independent of `into/blaze` for now.  The trade off for this is that you need to do the extra import

    import dask.array.blaze

Also, please note that at this stage you probably don't need to use Blaze.  Dask arrays are perfectly usable on their own.  Also, see http://dask.readthedocs.org/en/latest/array-blaze.html

**Comment by mfenner1** [comment]
Fair enough and it certainly makes sense.

The last example in the docs you link to:  http://dask.readthedocs.org/en/latest/array-blaze.html was the source of my `d=Data(x)` line.  And it won't work without the `import dask.array.blaze` line.  So, I would add that to the example and more generally, make a comment about it on the dask/blaze page.

Best,
MarkFe
