### ISSUE TITLE
Compile function to dask graph

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#411]
We should find a way (or many ways) to make it easy to write down custom dask graphs.

One option is the fully explicit solution in #408 . 

Another would be to write computations as Python functions, manipulate those functions a bit, and then use them to build the graph.

```python
@dask.compile
def f(x, y):
    a = g(x)
    b = f(y)
    return h(a, b)

>>> f(1, 2)
{'x': 1, 'y': 2, 'a': (g, 'x'), 'b': (f, 'y'), 'out': (h, 'a', 'b')}
```

Though we would need to be more careful about names.

This becomes more useful if we allow ourselves to execute some code in the function.  In particular loops and some compile-time control logic

```python
@dask.compile
def f(seq, x):
    data = map(load, seq)
    data2 = [clean(d) for d in data]
    results = []
    for i, a in enumerate(data2):
        for j, b in enumerate(data2):
            if i < j:
                results.append(process(a, b, x))
    return finish(results)
```

We want to actually execute some of these operations at runtime.  These operations include the map, the list comprehension, enumerate, the for loops, and the if clause.  For other operations, like load, clean, and process, we want to turn these into tasks in the graph.  It's not clear how best to specify which operations should be run at graph creation or graph execution time.

One might consider specifying the delayed functions in the decorator

```python
@dask.compile(delayed=[load, clean, process])
```

In which case this might just reduce to #408

Alternatively one might also consider specifying the data that should be treated lazily

```python
@dask.compile(delayed=[seq, x])
```

Or maybe there is some way to avoid asking the user to specify lazy functions entirely.

**Comment by jcrist** [comment]
If you limit the dask construction to only function calls (all control flow statements actually execute), I think I can do this with just an ast transform. This would be a fun sprint for today.

**Comment by mrocklin** [comment]
Small logic like the `i < j` is probably essential.

**Comment by eriknw** [comment]
If all of the `delayed` functions are from the global outer scope, then the following is one way to replace these functions at the time the function is called:
```python
import types
from toolz import curry, merge

@curry
def compile(func, delayed=()):
    def inner(*args, **kwargs):
        d = {x: MAKE_PROXY_HERE(func.__globals__[x]) for x in delayed
             if x in func.__globals__ and x in func.__code__.co_names}
        g = merge(func.__globals__, d)
        newfunc = types.FunctionType(func.__code__, g, func.__name__,
                                     func.__defaults__, func.__closure__)
        return newfunc(*args, **kwargs)
    return inner
```
Note that this is Python 3.  It is a little trickier to replace closures, but is definitely doable without scary hacking.  Since we have the names and values of the items used from outer scopes, it would be straightforward to come up with sane default behavior, such as proxying all callables except those in a blacklist (such as `map`, `enumerate`, etc.).

I think it may still be useful (or at least interesting) to explore AST traversal too.

**Comment by jcrist** [comment]
With some modifications to the above, I was able to produce the following:

```python
>>> from dask.wrapper import compile
>>> from numpy import arange

>>> @compile(delayed=[arange])
>>> def big_mean(n, m):
...     data = [arange(i*n, (i+1)*n) for i in range(m)]
...     sums = [i.sum() for i in data]
...     cnts = [i.size for i in data]
...     return sum(sums) / sum(cnts)

>>> res = big_mean(1000, 10)
>>> res.compute()
4999.5
```

In general, I don't like this - too much magic. But it's doable if desired.

**Comment by jcrist** [comment]
Also, if sum *isn't* delayed, you get a really interesting graph showing how python would unroll all the sum loops. Which was fun to see, but shows how much a danger doing this in a magical way can be. Better to be explicit than implicit.

**Comment by mrocklin** [comment]
I'm happy closing this for now.  Lets use `dask.imperative` for a while and see how it feels.
