### ISSUE TITLE
Profile function naming

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#413]
The profile currently prints names a bit oddly.  In particular

    (f, (g,))  -> f

    (lambda x: x,)  -> &lt;lambda&gt;

The first is also a problem in dot printing.

**Comment by jcrist** [comment]
I wrote something up, but I'm not sure if it's a good solution. Best way is to show some examples.

```
import numpy as np
import dask.array as da

x = np.arange(100).reshape((10, 10))
a = da.from_array(x, chunks=(5, 5))
res = (a.mean(axis=0).sum() + 4)
res._visualize()
```
![mydask](https://cloud.githubusercontent.com/assets/2783717/8735496/c7c836b4-2bd6-11e5-9f41-2fff41dec2c4.png)

**Comment by mrocklin** [comment]
I agree with you that the length of the label disrupts the visual effect of the dot graph.  It's fairly easy to fix that though with the following within dot

```python
s = name(task)
if len(s) > 10:
    s = s[:10] + '...'
```

For profiling though we can probably skip that curtailment.  

Thoughts on moving the paren to the right side of the function call?

**Comment by shoyer** [comment]
What about adding line breaks to the labels in the dot graph?

**Comment by jcrist** [comment]
I don't like that fix, that could result in truncated function names, missing close parens, etc... I'd prefer to just display the name of the top-level function for the task for the graph. Perhaps if there's nesting, something like `(foo, (...))` could work. For profiling though, I think this is good.

> Thoughts on moving the paren to the right side of the function call?

Could be done. I did it this way to match the internals of dask. No strong opinions here.

> What about adding line breaks to the labels in the dot graph?

I'm against doing this - the issue isn't that the circles are big, but that the text is too long to get a general sense of the flow. Also, some tasks (read_csv for example) create huge tasks, which will still be a problem even with line wrapping.

**Comment by mrocklin** [comment]
I see truncated function names and missing close parens as less bad than completely missing function names.  Often for nested tasks the important function is actually fairly deep within the task and the top-level function is somewhat irrelevant (e.g. `list`).  A `...` makes it somewhat unambiguous that there is more than what we see.  Leaving just the top-level doesn't give that impression.  I've had to explain what's going on a few times to people when sitting down with them.  I'm looking to make that conversation easier.  Alternatives welcome.

Moving the paren to the right matches how most people think of function calls.  I think that we should think in a lispy way internally but expose a non-lispy style externally whenever possible.

**Comment by jcrist** [comment]
Agree with the above, I just thought we should truncate at a nice break, rather than mid-string. Here's what I have now (just for graphs, profiling will use whole version). Prints top-level function if there are no sub-tasks, otherwise prints top-level function with closed parens around `...`. I think this is a good mix of succinctness and clarity when there are sub-tasks.

![mydask](https://cloud.githubusercontent.com/assets/2783717/8752452/c24da130-2c79-11e5-84ce-9a5672a6a1e8.png)

**Comment by mrocklin** [comment]
This seems better than what was around before.  So +1 for now.

I wonder if we should rotate the graphs to be left-right or if we could use ellipses rather than circles to avoid size blowup

**Comment by mrocklin** [comment]
Thoughts on the lambda printing?

**Comment by jcrist** [comment]
I think just printing `<lambda>` is the best we can do. The reason the profiler looks weird is because bokeh fails to properly escape html for the hovers, but this can be worked around by using a custom hover for now.
