### ISSUE TITLE
Should dask traverse down tuples, sets, and dicts?

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#419]
We currently traverse down lists within values/tasks but not tuples, lists, or dicts.

```python
In [1]: d = {'x': (sum, ('y', 'z')), 'y': 1, 'z': 2}

In [2]: from dask.async import get_sync as get

In [3]: get(d, 'x')
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

This would have worked if

```python
In [1]: d = {'x': (sum, ['y', 'z']), 'y': 1, 'z': 2}
```

This is somewhat convenient to have in #408 but may interfere with some basic assumptions that we've been making.

cc @eriknw @jcrist

**Comment by jcrist** [comment]
I say no, this increases complexity for very little gain. It also makes it almost impossible to pass in a string as a parameter to a task if that string matches a key. Tuples, sets, and dicts can all be created from lists, which we currently support.

**Comment by eriknw** [comment]
I agree with jcrist.  Let's keep the dask protocol simple and explicit.

**Comment by shoyer** [comment]
I commented in #421, but I think this would actually be a reasonable idea if we also added `quasiquote` as a way to explicitly identify literal arguments. The fall back rules in the dask specification are convenient but also error prone.

**Comment by mrocklin** [comment]
Closing this for now.  Using lists is sufficient for the other cases if you explicitly wrap them with calls to the collection, e.g. `(tuple, [1, 2, 3])`.  I like the idea of a quote function that explicitly creates these things, e.g.

    >>> quote((1, 2, 3))
    (tuple, [1, 2, 3])
