### ISSUE TITLE
Detach from mrocklin/dask

### ISSUE THREAD

**Issue by Carreau** [ContinuumIO/dask#43]
First I'd like to thanks @mrocklin for discussion on `dask.array` yesterday, I feel like the readme does not emphasis this part of the project. But that's my point of view. 

Also it seem that this is the main repository, though it's still appear as a fork of mrockling/dask which decrease the visibility bias the statistics. My I suggest asking GitHub to "detach" this repository as described [in their help section](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork) ?

**Comment by mrocklin** [comment]
Good plan.  I've sent a support request to github.  I'll try to revamp the README in the next day or two.  In the mean time I've been keeping [the docs](http://dask.readthedocs.org/) pretty up-to-date.

**Comment by Carreau** [comment]
Yes, I saw [the docs about arrays](http://dask.readthedocs.org/en/latest/array.html) 

I think it is missing "a faster drop-in replacement for numpy" catch phrase :-)

**Comment by shoyer** [comment]
I guess github never responded? strange....

**Comment by mrocklin** [comment]
Oh, they did.  I think this got stalled within Continuum.  Will push again.

**Comment by mrocklin** [comment]
Done.
