### ISSUE TITLE
Implementing np.histogram equivalent

### ISSUE THREAD

**Issue by gabrielelanaro** [ContinuumIO/dask#431]
Hi, I would like to have some input on how to implement histogram (binning) using dask. It should be possible to do this in parallel, using the following steps:

1) determine bins (user-provided, or using max/min)
2) for each block, make a local histogram
3) sum the local histograms (for example with np.histogram) to obtain the final histogram
4) optionally normalize

Would a strategy like this be possible in the dask framework? If so, I'd appreciate some pointers

related #334

**Comment by mrocklin** [comment]
Hi @gabrielelanaro !

What you suggest is definitely doable in the case of user-provided bins.  I'd be happy to add this if it's valuable for you or to help you add it if you wanted to play around with the library.  The min/max solution would also work but would probably require an extra pass and so might be significantly more expensive depending on the context.

A good alternative parallel algorithm to pre-computing min/max would be to compute approximate percentiles which give much of the same information.

```python
In [1]: import dask.array as da

In [2]: x = da.random.normal(10, 0.1, size=(1000,), chunks=(100,))

In [3]: q = [0, 10, 40, 60, 90, 100] # values at which we want the percentile

In [4]: da.percentile(x, q).compute()
Out[4]: 
array([  9.83730711,   9.90105795,   9.99332926,  10.04358186,
        10.14326209,  10.35795832])
```

**Comment by mrocklin** [comment]
If you're interested in trying this out yourself I've written this doc that should give some basic pointers to start.  I would also welcome feedback on where that document is confusing or how it could better explain this process.

https://github.com/ContinuumIO/dask/pull/432/files

**Comment by gabrielelanaro** [comment]
Thanks so much! Yes I'll try to implement it myself and I'll get back here when I get stuck or for  questions. The document is in fact very helpful, earlier I tried to look at the https://github.com/ContinuumIO/dask/blob/master/dask/array/reductions.py#L16 module, but I didn't understand much on first sight.

**Comment by mrocklin** [comment]
There are some internal functions, like `atop`, that one can use to build these things more easily once you get used to them.  They're somewhat advanced technology though.  For cases like `np.histogram` building dictionaries by hand is probably more direct and also more educational.  

Please ask for help if you get stuck.  I'm currently thinking about how to make this process easier for new developers so I'm quite curious to see how you get on.  The gitter channel might be a good place for more real-time conversation.  https://gitter.im/ContinuumIO/dask

**Comment by gabrielelanaro** [comment]
@mrocklin hi implemented a first, very very simple version that takes as input a flattened Array and performs the operations metioned above.

    tokens = iter(['1', '2', '3', '4', '5', '6'])
    def hist(v, bins):
        nchunks = len(v.chunks[0])

        name1 = 'hist_' + next(tokens)
        # Map the histogram to all bins
        chunks = ((1,) * nchunks, (len(bins),))

        def block_hist(x):    
            return np.histogram(x, bins)[0][np.newaxis]

        dsk = { (name1, i, 0) : (block_hist, (x.name, i)) 
                                   for i in range(nchunks)}

        dsk.update(v.dask)

        dtype = 'i'
        mapped = da.Array(dsk, name1, chunks, dtype)
        return mapped.sum(axis=0)

    x = da.from_array(np.arange(20), chunks=5)
    bins = np.arange(0, 20, 2)
    hist(x, bins).compute()

It wasn't too easy, those are the parts I got stuck:
1) couldn't find the tokens variable, I made something on the spot.
2) It took me a while to figure out how the chunks translate into shapes. The a-ha was when I realized that if I want to produce an array of dimension (5, 4) I have to define chunks that satisfy ( <tuple that sum to 5>, <tuple that sum to 4>). Also, it was helpful to populate the dictionary explicitly (name, 0,0) (name, 0, 1) etc.
3) When we do operations on chunks, it took me a while to figure out the difference between:

    ('hist_1', 0, 0) : (operation, v.name)

 That operates on the whole array. Versus:
  
    ('hist_1, 0, 0) : (operation, (v.name, 1))

That operates on the actual chunk

Now I'm trying to extend the hist implementation above, by letting it do histogram on arbitrarily-shaped arrays (not just flattened). Is there a pattern for that? I guess a simple thing would be to simply flatten the array and call the original.

**Comment by mrocklin** [comment]
Thanks for the detailed feedback @gabrielelanaro .  I've responded to some of it in https://github.com/ContinuumIO/dask/pull/436

For n-dimensionally arrays I recommend getting a flat sequence of all input keys with the following

    dask.core.flatten(v._keys())

And then do what you're doing now.

In general your implementation seems pretty good to me.  Please let me know if there are things that you noticed were confusing that the recent changes to the documentation don't cover.

**Comment by gabrielelanaro** [comment]
@mrocklin reference docs looks good so far. Also, I had no problems with the extension of the implementation using v._keys() .

Would this function belong to the dask library? If so I can make a PR after making a proper implementation (better mimic numpy + tests + docs). If not, we may consider this issue resolved.

**Comment by mrocklin** [comment]
Yes, this would be very good to have within dask.array.  

The main extra point I would want to see would be good error messages when users try to use parts of the `np.histogram` interface that this doesn't implement.  Ideally those error messages point them to correct behavior.

**Comment by gabrielelanaro** [comment]
I've been working on an implementation, I have a few questions:

1) I added the code and tests to the wrap module (because it sort of wraps the np.histogram code), let me know if this function belong to somewhere else.
2) I'm implementing the 'weights' feature. Weights is an array that has the same block structure as the input array, and we have to call numpy.histogram on the matching chunks. The current code uses flatten(a._keys()) to get all the keys from one array. How to extend this to be able to get matching keys in the two arrays?

Current code:

https://github.com/gabrielelanaro/dask/blob/feature-hist/dask/array/wrap.py#L140-L141

**Comment by mrocklin** [comment]
Assuming that the two arrays have the same block structure then yes, `flatten` on `_keys` will work appropriately.  Further comments on the PR itself.

**Comment by gabrielelanaro** [comment]
Closing this as it is now merged
