### ISSUE TITLE
da.to_hdf5() fails when array is not evenly divisible by chunk size

### ISSUE THREAD

**Issue by venabled** [ContinuumIO/dask#451]
When a dask.array has some chunks not equal to the requested chunk/block size, dumping this array to hdf5 using da.to_hdf5 throws: ```TypeError:  Exception in remote process```. In my example, I have an array with requested chunk shape (250, 250), and the last chunk has size (250, 125). 

If I ask for the result using da.compute(), it returns the correct result, so it must just be an assumption in broadcasting in the to_hdf5 convenience function.

Here's the result: 

```
TypeError:  Exception in remote process

Can't broadcast (250, 125) -> (250, 250)
```

**Comment by mrocklin** [comment]
Hrm, can you run this sequentially and provide the full traceback

```python
import dask
from dask.async import get_sync
dask.set_options(get=get_sync)

# do whatever you did before
```

This will help to identify from where the problem originated.

**Comment by venabled** [comment]
Actually this is an error on my end. I miscalculated the chunk size returned from my mapper, so the actual chunks returned by the final computation weren't the correct size. Closing.

**Comment by mrocklin** [comment]
Ah, I see.

I'm curious how we could help handle `chunks` with `map_blocks` for users.  It's hard to specify chunks exactly with uneven chunksizes.  This feels somewhat brittle.
