### ISSUE TITLE
Multiprocessing RuntimeError ('cannot join current thread')

### ISSUE THREAD

**Issue by jrmontag** [ContinuumIO/dask#478]
I'm observing a dask bag creation error where it seems that the dask task appears to run and finish correctly, but the multiprocessing code returns the following exception:

``Exception RuntimeError: RuntimeError('cannot join current thread',) in <Finalize object, dead> ignored``

This is running Python 2.7.3 in IPython 2.2.0 on a Ubuntu 12.04.5 LTS server. Let me know what other useful information I can provide!

**Comment by mrocklin** [comment]
I can reproduce this by using Python 2.7.3 as follows:

```
mrocklin@workstation:~$ conda create -y -n py273 python=2.7.3 dask ipython
mrocklin@workstation:~$ source activate py273
(py273)mrocklin@workstation:~$ ipython
```

```python
In [1]: import dask.bag as db

In [2]: db.from_sequence([1, 2, 3]).map(lambda x: x + 1).compute()
Out[2]: [2, 3, 4]

In [3]: Exception RuntimeError: RuntimeError('cannot join current thread',) in <Finalize object, dead> ignored
```

Although this doesn't seem to be a problem in recent versions of Python 2.7.  I'm not yet sure how we should handle bugs in older Python versions.

**Comment by mrocklin** [comment]
Given that this has been fixed in newer versions of Python and that it isn't a catastrophic failure (but mostly just a warning) I'm going to close this for now.  Please feel free to reopen if this ends up
