### ISSUE TITLE
KeyError when running stack/concatenate

### ISSUE THREAD

**Issue by jakirkham** [ContinuumIO/dask#48]
Below is how I ran into the error with the resulting traceback. I am using Dask version 0.2.6, Python 2.7.6, and NumPy 1.7.0. For what its worth, I also tried calling `c = dask.array.stack([a, b], axis=0)`, but it made no difference. Also, I tried `c.compute()`, but this had the same result. Lastly, had this result with `dask.array.concatenate`, as well, but with a slightly different error ( `KeyError: ('concatenate-1', 0, 0)` ) otherwise the traceback was the same. Repetition in either case results in the number in the key name increasing (e.g. `concatenate-2`). Calling `numpy.array(a)` or `numpy.array(b)` behaved correctly.

    >>> import dask
    >>> import dask.array
    >>> import numpy
    >>> 
    >>> a = dask.array.empty(shape=(10,10), blockshape=(10,10), dtype=float)
    >>> b = dask.array.empty(shape=(10,10), blockshape=(10,10), dtype=float)
    >>> c = dask.array.stack([a, b])
    >>> 
    >>> numpy.array(c)

    ---------------------------------------------------------------------------
    KeyError                                  Traceback (most recent call last)
    <ipython-input-1-646ff5d0cb10> in <module>()
          7 c = dask.array.stack([a, b])
          8 
    ----> 9 numpy.array(c)
    
    /xopt_ilastik/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dask-0.2.6-py2.7.egg/dask/array/core.pyc in __array__(self, dtype, **kwargs)
        402 
        403     def __array__(self, dtype=None, **kwargs):
    --> 404         x = self.compute()
        405         if dtype and x.dtype != dtype:
        406             x = x.astype(dtype)
    
    /xopt_ilastik/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dask-0.2.6-py2.7.egg/dask/array/core.pyc in compute(self, **kwargs)
        437 
        438     def compute(self, **kwargs):
    --> 439         result = get(self.dask, self._keys(), **kwargs)
        440         if self.shape:
        441             result = rec_concatenate(result)
    
    /xopt_ilastik/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dask-0.2.6-py2.7.egg/dask/array/core.pyc in get(dsk, keys, get, **kwargs)
        629     dsk3 = inline_functions(dsk2, fast_functions=fast_functions)
        630     dsk4 = dsk3
    --> 631     return get(dsk4, keys, **kwargs)
        632 
        633 
    
    /xopt_ilastik/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dask-0.2.6-py2.7.egg/dask/threaded.pyc in get(dsk, result, nthreads, cache, debug_counts, **kwargs)
         46         results = get_async(pool.apply_async, nthreads, dsk, result,
         47                             cache=cache, debug_counts=debug_counts,
    ---> 48                             queue=queue, **kwargs)
         49     finally:
         50         pool.close()
    
    /xopt_ilastik/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dask-0.2.6-py2.7.egg/dask/async.pyc in get_async(apply_async, num_workers, dsk, result, cache, debug_counts, queue, **kwargs)
        440             raise type(res)(" Execption in remote Process\n\n"
        441                 + str(res) + "\n\nTraceback:\n" + tb)
    --> 442         finish_task(dsk, key, res, state, results)
        443         while state['ready'] and len(state['running']) < num_workers:
        444             fire_task()
    
    /xopt_ilastik/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dask-0.2.6-py2.7.egg/dask/async.pyc in finish_task(dsk, key, result, state, results)
        257 
        258     for dep in state['dependents'][key]:
    --> 259         s = state['waiting'][dep]
        260         s.remove(key)
        261         if not s:
    
    KeyError: ('stack-1', 0, 0, 0)

**Comment by mrocklin** [comment]
Thank you.  This exposed a subtle bug in the async scheduler.  Fixed in https://github.com/ContinuumIO/dask/commit/47402029d02536d950d89dd1fa9174a4f93d9483

```python
In [1]: import dask

In [2]: import dask.array

In [3]: import numpy

In [4]: a = dask.array.empty(shape=(10,10), blockshape=(10,10), dtype=float)

In [5]: b = dask.array.empty(shape=(10,10), blockshape=(10,10), dtype=float)

In [6]: c = dask.array.stack([a, b])

In [7]: numpy.array(c)
Out[7]: 
array([[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]])

In [8]: numpy.array(c).shape
Out[8]: (2, 10, 10)
```

**Comment by jakirkham** [comment]
Of course, glad to help. I had a question about your change so added a line note to your commit. Please let me know your thoughts.
