### ISSUE TITLE
Increase dask.Bag extendibility

### ISSUE THREAD

**Issue by StuartAxelOwen** [ContinuumIO/dask#484]
`dask.Bag` is a beautiful thing - it allows for method chaining and stream processing while decoupling program execution from just Python iterators.  In my eyes, it creates a wonderful interface to add more specific or niche tools, much like the `numpy.array`.  There is just one thing standing in the way!

Ideally, to build on top of `dask.Bag` you would only need to extend it:

```python
class DictBag(Bag):
    def get(self, key, default=None):
        return self.map(lambda d: d.get(key, default=default))
```

And go along on your merry way.  This doesn't work though, as the second you try to use `get` again in your chain, you'll get an attribute error - `dask.Bag` doesn't have a `get` method, silly!  This is because every chained result is returning a newly constructed `Bag`.

This _can_ be worked around, but it involves redefining every method you want to use in the extended class, and it introduces a lot of opportunity for programmer error.

Instead, we could add something like a `Bag._bag` method that would be responsible for constructing bags, and which could easily be overridden to allow `Bag` methods to return the extended type.

```python
class DictBag(Bag):
    @classmethod
    def _bag(cls, *args, **kwargs):
        return DictBag(*args, **kwargs)

    def get(self, key, default=None):
        return self.map(lambda d: d.get(key, default=default))
```

With this, any call to a chaining method will give you back the proper type!  

Based on my initial investigation, it looks like we'd only need to add the `_bag` class method and change the chained methods to return using the `_bag` constructor instead of the `Bag` constructor.

**Comment by StuartAxelOwen** [comment]
You can find an example of using this technique in [DataStreams](https://github.com/StuartAxelOwen/datastreams/blob/master/datastreams/dictstreams.py), which was a similar method chaining/stream processing library.  The linked class is a DictStream - which thanks to the above technique, only required a tenth of the methods to be defined, and still allowed full utilization of the core library features.

**Comment by mrocklin** [comment]
I agree that it would be good to take steps to enable others others to extend dask.bag.  Adding a `_bag` method as described above seems reasonable.  Using `type(self)(dsk, name, npartitions)` might work as well.  In either case we're limited to the interface of the constructor.

I would only want to do this if there were `Bag` subclasses around the corner.  Is this your intention @StuartAxelOwen or is this currently in the "wouldn't it be cool if" stages?

**Comment by StuartAxelOwen** [comment]
It certainly is - I'm working on something that uses `Bag` as its base, and I'd prefer not to maintain a fork of `dask` just for that :stuck_out_tongue:   

I'd be happy to submit a PR.

**Comment by mrocklin** [comment]
Such a PR would be welcome.

I have a very slight preference to use `type(self)` over a `_bag` method.

**Comment by mrocklin** [comment]
Closing this due to #484

**Comment by StuartAxelOwen** [comment]
I'm getting the feeling that redoing the method chaining was only half the battle - the `Bag` constructors are currently all directly tied to the `Bag` type.  Currently the cost of just calling `OtherBag(*bag.from_sequence(things)._args)` is essentially nothing, but it is a possible point of divergence.  Assuming bag construction stays stable, this shouldn't be a problem... But something about it feels... Something.  Nothing to do till real concerns arise, but felt it was appropriate to share my thoughts.
