### ISSUE TITLE
Caching option for dask.DataFrame

### ISSUE THREAD

**Issue by dataisle** [ContinuumIO/dask#488]
As part of the analytical monitoring related workflow, we find querying the same type of data over and over again and there is currently no way to persist the dataframes in-memory for a near-realtime and interactive analysis.  This may also lead into  "aggressive caching" bit that i know @mrocklin is interested in solving for as well.

**Comment by mrocklin** [comment]
For single node operation the solution is to back a dask.dataframe off of a pandas.dataframe in the following way.

    df = dd.from_pandas(df.compute(), npartition=10)

However from our talks I believe that @dataisle is more interested in the distributed memory case, where indeed no such solution exists.  

This is more a question about the distributed scheduler and how we can choose to keep results in memory on the workers.  I see this problem as two parts

1.  How the client tells the scheduler that we want to keep data on the workers
2.  A quick optimization that `culls` incoming graphs of tasks whose results are already in worker data.

The second form of caching that we discussed was about opportunistically caching intermediate results without the user asking for it.  A brief writeup for what I was thinking about previously exists [here](https://github.com/mrocklin/sbe/blob/master/caching.md).  This topic feels somewhat orthogonal though.

**Comment by mrocklin** [comment]
cc @cowlicks, who has been thinking about distributed scheduling recently.

**Comment by dataisle** [comment]
Thanks. Opportunistic caching seems like a really awesome end-state. i am in the middle of creating a computation setup with medium size data (around 60GB) using dask.distributed and i think i could potentially play around the scheduler API to let the workers know to cache a dataframe.

How are you thinking about the optimization that culls the precomputed elements of the graphs?

**Comment by mrocklin** [comment]
It's in `dask.optimize.cull`

* [Docs](http://dask.pydata.org/en/latest/optimize.html)
* [Code](https://github.com/ContinuumIO/dask/blob/master/dask/optimize.py#L9-L33)

**Comment by dataisle** [comment]
Cool. thanks.

**Comment by mrocklin** [comment]
So when a scheduler [receives a graph from the client](https://github.com/ContinuumIO/dask/blob/master/dask/distributed/scheduler.py#L573) it can cull the graph based on the [keys found in the workers](https://github.com/ContinuumIO/dask/blob/master/dask/distributed/scheduler.py#L73-L76)

**Comment by mrocklin** [comment]
I can find some time to do this tomorrow or maybe later this afternoon.

**Comment by mrocklin** [comment]
Assuming you don't beat me too it that is :)

**Comment by dataisle** [comment]
haha, i am quite slow, just started looking into the code base today.
