### ISSUE TITLE
Add `numpy.where` equivalent

### ISSUE THREAD

**Issue by jakirkham** [ContinuumIO/dask#49]
If I'm just missing this, I'm sorry I didn't catch it and am sorry to trouble you over it. If not, my proposal is below. Please let me know your thoughts. Also, I don't know all the details of your system. So, if there is something I have missed, please let me know.

I think it would be really cool to have a `numpy.where` type function in `dask`, especially, as the arrays themselves cannot be set. Though, using a `numpy.where` approach maybe setting in certain context would be acceptable, as well. I'm thinking this could just behave as a simple branch that is inserted into the the graph. Additionally, if the condition is trivial like a single bool, this could result in removal of the unused portion of the graph.

**Comment by mrocklin** [comment]
Good idea.  Implemented in https://github.com/ContinuumIO/dask/pull/50 .  Feedback and play-testing welcome.

**Comment by jakirkham** [comment]
Nifty. Thanks. Nice to see it was such an easy add. I'll have to play with it and see how it goes.
