### ISSUE TITLE
Another dask.array bug with scalar arrays

### ISSUE THREAD

**Issue by shoyer** [ContinuumIO/dask#494]
```
import dask.array as da
import numpy as np

x = da.from_array(np.array(1.0), chunks=())
(x == x).all().compute()
# IndexError: tuple index out of range

# or alternatively
(x + x).sum().compute()
```

Arguably, the source of this bug is the fact that numpy turns 0d arrays into scalars after binary operations:
```
In [8]: a = np.array(1.0)

In [9]: a + a
Out[9]: 2.0

In [10]: type(a + a)
Out[10]: numpy.float64
```

Unfortunately, dask still needs to work around this...

**Comment by mrocklin** [comment]
Fixed in #495

**Comment by mrocklin** [comment]
(cheaply/hackily)

**Comment by shoyer** [comment]
What do you think about explicitly inserting calls to `np.array` into the dask task graph for binary operations on scalar arrays?

**Comment by mrocklin** [comment]
I don't think that that was the problem here.  The results in these cases are often scalar arrays.  The problem was in the administrative code around numpy.

I may not understand the deeper problem though.  I'm not currently opposed to inserting calls to `np.array` if they're likely to help a decent class of problems.

**Comment by shoyer** [comment]
You're right -- it looks like aggregation functions were entirely broken on 0d arrays, even if they aren't actually scalars:
```
In [12]: x = da.from_array(np.array(1.0), chunks=())

In [13]: x.sum()
Out[13]: dask.array<x_5, shape=(), chunks=(), dtype=float64>

In [14]: x.sum().compute()
# IndexError: tuple index out of range
```

**Comment by mrocklin** [comment]
I treat this as a particular problem with the administrative functions that can be fixed after a few rounds of things like this issue.  Are you ok with this approach?  Also, can we merge #495 ?

**Comment by shoyer** [comment]
Yep, I think this is fine. I might try to come up with some more comprehensive tests to proactively identify these issues.

**Comment by mrocklin** [comment]
That would be good.
