### ISSUE TITLE
dataframe.index.nunique raises with TypeError

### ISSUE THREAD

**Issue by TomAugspurger** [ContinuumIO/dask#517]
```python

In [17]: import dask.dataframe as dd

In [18]: df = dd.from_pandas(pd.DataFrame(np.random.randn(100, 2), columns=['a', 'b']), 2)

In [19]: df.index.nunique().compute()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-38401c5f5758> in <module>()
----> 1 df.index.nunique().compute()

...

The original exception and traceback follow below:

cannot concatenate a non-NDFrame object
```

That's a pandas error (from `pd.concact`). Just a report right now, haven't looked into it. I did see https://github.com/ContinuumIO/dask/pull/322 which implemented `nunique.`

**Comment by cowlicks** [comment]
So far I've tracked this down to `apply_concat_apply`. We are trying to use `pd.concat` to concatenate `index` objects. I'm looking the proper way to do this now.

**Comment by TomAugspurger** [comment]
Again, sorry but I haven't looked at the code so I'm just guessing this would work. But something like this should work in this case:

```python
In [27]: from functools import reduce

In [28]: import pandas.util.testing as tm

In [29]: idxs = [tm.makeIntIndex(i * 10) for i in range(1, 4)]

In [30]: reduce(lambda a, b: a | b, idxs)
Out[30]:
Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
           dtype='int64')
```

Not quite a `concat` since it won't contain duplicates, but that doesn't matter in this case since we're going to `nunique` anyway.
