### ISSUE TITLE
Support for __len__

### ISSUE THREAD

**Issue by jakirkham** [ContinuumIO/dask#54]
NumPy enables `__len__` to return the shape at axis `0`. If the array is a dimensionless scalar, it will fail with `TypeError: len() of unsized object`. Hopefully, this is an easy add.

**Comment by mrocklin** [comment]
It is an easy add.  Do you have any interest in adding it?  I've heard that once you get a contributor hooked they stay on for a while :)

**Comment by jakirkham** [comment]
Sure, I can try. I'll take a look at it this weekend.
