### ISSUE TITLE
Add `shape` kwarg to `dask.array.arange`.

### ISSUE THREAD

**Issue by cowlicks** [ContinuumIO/dask#541]
This would be useful for examples since we often do:
```python
arr = np.arange(100).reshape(10, 10)
darr = da.from_array(a, chunks=(5, 5)
```
but this is limited to arrays that fit in-memory since we have to create the numpy array first. I'd like something like:
```python
darr = da.arange(100, shape=(10, 10), chunks=(5, 5))
```

**Comment by mrocklin** [comment]
I also do this a lot and find it kind of kludgy.  At the same time I'm concerned that adding a `shape` kwarg to `arange` makes a promise that we can not keep.

**Comment by mrocklin** [comment]
I think I'm -1 on this because it deviates from the NumPy API and doesn't satisfy the "works on out-of-core datasets" promise.  I'd like to close.

**Comment by cowlicks** [comment]
Closing in favor of a `.reshape` method.
