### ISSUE TITLE
Conditional fuse

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#549]
We have a few optimizations that fuse tasks together

*  `fuse`: merge linear chains
*  `inline`: merge only certain tasks, even if this duplicates work

With the introduction of caching a full global `fuse` becomes less attractive because it diminishes our ability to find good caching points.  However we do still want to fuse *some* operations, notably getitem in arrays and all of the column-store load operations in dask.dataframe.  

What is the best way to create an optimization that fuses only certain kinds of operations but only when they occur in linear chains?  Is this a new function?  An alteration of an existing one?

cc @eriknw and @jcrist

**Comment by eriknw** [comment]
Good problem statement.  I can work on this tomorrow.

**Comment by mrocklin** [comment]
Actually, I may want to handle my immediate need with another method.  The priority of this may have just dropped down.

**Comment by mrocklin** [comment]
Closing.
