### ISSUE TITLE
Consider better node label representation of dot_graph

### ISSUE THREAD

**Issue by sinhrks** [ContinuumIO/dask#560]
Even after #556, ``DataFrame`` ops name is little long because of hash id. Thus, ``dot_graph`` output is little difficult to read. How about adding an keyword option to ``dot_graph`` which limit the max character length of nodes.

#### Current output (DataFrame.groupby().mean() with 2 partitions.

![index](https://cloud.githubusercontent.com/assets/1696302/9155154/84ceb97a-3ee9-11e5-800d-da57d86fa66c.png)

Would like to ask what the kw name and its default should be. My idea is  ``label_length``, and its default is 20. It only touches operation name leaving partition number as it is.

**Comment by mrocklin** [comment]
We could also identify hash strings (match `[0-9a-f]{32}`) and replace them with a symbol like `#`.

**Comment by jcrist** [comment]
I vote for replacing the hash with `#`. The only (potential) downside is that keys will repeat themselves in the graph if the same computation is done more than once. But the shape of the graph is the important part.

**Comment by mrocklin** [comment]
I can take care of this tomorrow if no one beats me too it.  Looks like we call `str(dep)` at one point.  This should probably be a more interesting function.

**Comment by sinhrks** [comment]
Yes, replacing hash looks better idea than splitting by length.

**Comment by sinhrks** [comment]
Gr8! It can be nicer if we can replace each hash enumerating up, like ```#1, #2, #3...```. Because we may want to distinguish each data source (like merge example below). Let me reopen if agreed.

![2015-08-11 1 50 20](https://cloud.githubusercontent.com/assets/1696302/9177296/60331f1a-3fcb-11e5-8320-24a1514cd250.png)

**Comment by mrocklin** [comment]
Sounds reasonable to me
