### ISSUE TITLE
Minimum time threshold before showing progress bars

### ISSUE THREAD

**Issue by shoyer** [ContinuumIO/dask#584]
Just started playing around with dask progress bars. These are very handy -- thanks!

I especially like the ability to register a progress bar and see it for all operations.

One annoyance when using this with xray datasets is that xray operations often involve some very small calculations (e.g., to verify aligned indexes) before doing calculations. These take a fraction of a second, so showing a progress bar is not very useful:
```
[########################################] | 100% Completed |  0.1s
[########################################] | 100% Completed |  0.1s
[########################################] | 100% Completed |  0.1s
[########################################] | 100% Completed |  0.1s
[########################################] | 100% Completed |  0.1s
[########################################] | 100% Completed |  0.1s
```

I wonder if we could add some optional minimum time threshold before displaying the progress bar?

**Comment by jcrist** [comment]
Could definitely do that. If you know an operation is cheap, you could also turn it off (unregister it), or just use it in the contextmanager form. I'm happy to add this option if desired though, as long as it's not the default.

**Comment by mrocklin** [comment]
This seems reasonable to me for any computation that takes less than, say 500ms.

**Comment by mrocklin** [comment]
I only actually value the progressbar for longer running computations.  In @shoyer's case he has lots of small computations that are getting in the way.  These are in library code and so it's not convenient to wrap or unwrap them.  

We all agree that an option with a minimum time before visible is good.  We potentially disagree on what that default should be.  Fortunately most of the work is independent of the choice of this default.

**Comment by mrocklin** [comment]
Actually @jcrist 's suggestion of zero for the default minimum time might be a sane default just because it is a natural choice (not at all subjective).  I don't mind saying the following when I start up.

```Python
ProgressBar(minimum=0.500).register()
```

**Comment by jcrist** [comment]
I'll throw this in with the other progressbar changes in #581.

**Comment by shoyer** [comment]
Agreed, I don't mind specifying the minimum time explicitly.
