### ISSUE TITLE
Additional improvement for da.image.imread

### ISSUE THREAD

**Issue by sinhrks** [ContinuumIO/dask#585]
I think following 2 improvements make the function better.

#### 1. Allow custom ``imread`` function.

Some prefer ``opencv`` which reads color in BGR order, otherwise ``skimage`` reads in RGB order. Adding ``dialect`` option (like ``dialect='skimage'`` or ``dialect='cv'``) or accept different file read function may better.

#### 2. Allow custom preprocessing function.

In image processing, input images may have different sizes. In these case, preprocessing is needed between image read and array creation. This preprocessing function must return the same size of array on user's responsibility.

**Comment by mrocklin** [comment]
Nice ideas.  https://github.com/ContinuumIO/dask/pull/586
