### ISSUE TITLE
Tokenize as part of the public API?

### ISSUE THREAD

**Issue by shoyer** [ContinuumIO/dask#593]
I'd like to clarify if `dask.base.tokenize` is part of the public API or not.

Basically, I'd like to replicate the rules used for `name` by dask's `imread` and `read_csv` when opening up a netCDF file in xray. To do this, it would be nice to be able to use dask's `tokenize`.

**Comment by jcrist** [comment]
I'd say you should be able to use it, but be aware that there also might be changes in the future as we work more on the deterministic names.

**Comment by mrocklin** [comment]
This could be two questions:

1.  Can we depend on the future existence of the function `dask.base.tokenize`
2.  Can we depend on the consistent operation of this function.

I'm comfortable saying "yes" to 1 with moderately high probability and "no" to 2 with moderately high probability.

**Comment by shoyer** [comment]
I'm happy with those constraints. As long as tokenize has a consistent signature, I'm happy. The goal is only to produce results that are consistent with dask -- they don't need to be fixed across versions.

**Comment by mrocklin** [comment]
@jcrist do you anticipate any API changes?  If not then we can probably close this.

**Comment by jcrist** [comment]
I don't. Implementation will probably change some, but the api is probably solid.
