### ISSUE TITLE
impossible to call _visualize

### ISSUE THREAD

**Issue by wiso** [ContinuumIO/dask#603]
from dask import dataframe
    import numpy as np
    import pandas as pd                 
    d = pd.DataFrame({'x': np.arange(10, dtype=float)})
    dd = dataframe.from_pandas(d, 2)
    dd._visualize()

error:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "dask/base.py", line 25, in _visualize
        return self.visualize(optimize_graph)
      File "dask/base.py", line 19, in visualize
        return visualize(self, filename=filename, optimize_graph=optimize_graph)
      File "dask/base.py", line 76, in visualize
        return dot_graph(dsk, filename=filename)
      File "dask/dot.py", line 135, in dot_graph
        g.save(filename + '.dot')
    TypeError: unsupported operand type(s) for +: 'bool' and 'str'

**Comment by jcrist** [comment]
Try working off master, this has been fixed.

```
from dask import dataframe
import numpy as np
import pandas as pd                 
d = pd.DataFrame({'x': np.arange(10, dtype=float)})
dd = dataframe.from_pandas(d, 2)
dd.visualize()
```

Also, `_visualize` has been deprecated in favor of `visualize`.

**Comment by jcrist** [comment]
Actually, you're right. This doesn't work for `_visualize`, just for `visualize`. Thanks for the fix!
