### ISSUE TITLE
into -> odo name change

### ISSUE THREAD

**Issue by cowlicks** [ContinuumIO/dask#62]
It looks like "into" has become "odo" with some small api changes ([link](http://comments.gmane.org/gmane.comp.python.pydata/3607)). Into is still available but dask should probably switch to odo. This looks like it will be pretty easy, `grep -r into . | wc -l` shows only 39 instances of into.

**Comment by mrocklin** [comment]
I'd actually like to pull the into and blaze stuff from dask into the odo/blaze repositories.  The renaming should presumably happen during that transfer.

**Comment by cowlicks** [comment]
So basically: `dask/dask/array/into.py` and `dask/dask/bag/into.py` go to `odo/odo/backends/dask.py`. And `dask/dask/array/blaze.py` goes to `blaze/blaze/compute/dask.py`?

**Comment by mrocklin** [comment]
Yes.  That sounds about right to me.
