### ISSUE TITLE
Linspace and arange functions

### ISSUE THREAD

**Issue by mrocklin** [ContinuumIO/dask#65]
Functions like `linspace` and `arange` might be interesting problems to work out for people new to dask graphs.  They would be useful to have too.

**Comment by mrocklin** [comment]
This implementation of the `eye` function might be a good model here.  http://dask.readthedocs.org/en/latest/array-design.html#example-eye-function

**Comment by cowlicks** [comment]
Should be closed by #115 and #136 @mrocklin ping
