### ISSUE TITLE
Add `networkx` to the requirements

### ISSUE THREAD

**Issue by jakirkham** [ContinuumIO/dask#67]
Appears to be used in some test cases. As it looks to be pure Python, it may be worth just adding to `requirements.txt`.

**Comment by mrocklin** [comment]
I think that it is only used in the `into/odo` parts of dask which are being migrated over to that library in https://github.com/ContinuumIO/odo/pull/128

**Comment by cowlicks** [comment]
Likewise with Blaze, it is required for the full test suite, but is being moved out to Blaze itself.
