### ISSUE TITLE
Some nan functions don't exist for certain versions of NumPy

### ISSUE THREAD

**Issue by jakirkham** [ContinuumIO/dask#70]
The following functions `nanmean`, `nanstd`, `nanvar` are not defined until NumPy 1.8.0. It would be nice if they weren't explicitly required.

**Comment by mrocklin** [comment]
Yes, we should probably guard these as we guard [nanprod](https://github.com/ContinuumIO/dask/blob/master/dask/array/reductions.py#L100-L103)

**Comment by jakirkham** [comment]
That seems perfectly reasonable. I started doing that, but I think they were being imported [dask/array/\_\_init\_\_.py#3f5e6e69137be3b4ffffc7cc3390d19d6c6b73e5]( https://github.com/ContinuumIO/dask/blob/3f5e6e69137be3b4ffffc7cc3390d19d6c6b73e5/dask/array/__init__.py ). Is it ok if this is eliminated? I noticed that you were just using `nansum`. So, I figured it would be fine to have your functions and skip the wrappings, which I did here ( https://github.com/jakirkham/dask/tree/numpy_1_7_support ). However, I ran into another surprise, which is `nansum` does not supply the `keepdims` argument. So, whatever solution is settled upon should probably have a workaround for `keepdims`, as well.

**Comment by mrocklin** [comment]
They should probably be imported in `__init__.py` if they are available.  Not sure on the least ugly way to do this (maybe `__all__` in reductions.py?).

Skipping just the wrappings sounds great.

Arg, not supporting keepdims is a pain.   At the moment I don't see a clear way around this other than by fundamentally changing how we do reductions.  This might require some cleverness but is probably possible.  Thoughts?

**Comment by jakirkham** [comment]
Using `__all__` seems reasonable.

Good to hear.

As for the last bit, I think this should be doable. I tried adding a wrapper function called `keepdims_wrapper`, which appears to work ( https://github.com/jakirkham/dask/commit/ab777ff94c8240ba6090eb238dcc1cd3ccde6360 ). It could be applied at the reduction stage (as done in the commit), which guarantees that all functions used have `keepdims` of some sort. Alternatively, it could be applied earlier when wrapping all the `numpy` functions, which would reduce the performance hit of doing the actual wrapping and inspection.

**Comment by jakirkham** [comment]
Nevermind, it appears following the last case is required.
