### ISSUE TITLE
Top level function for simultaneously storing multiple arrays at once

### ISSUE THREAD

**Issue by shoyer** [ContinuumIO/dask#84]
Given the overhead of starting the task scheduler, it would be useful to support storing a bunch of arrays simultaneously.

For example, saving a netCDF file will often involve writing ~10 arrays to a single file on disk.

**Comment by mrocklin** [comment]
We could provide a flag to the `store` method that prevented immediate evaluation and then pass many such lazy results to the compute method at once.  

Alternatively is there a spelling you think would be good here?

**Comment by shoyer** [comment]
I was thinking `da.store(source, destination)` could simply do an isinstance check see if `source ` is a dask array, or otherwise assume it's an iterable of dask arrays.

**Comment by mrocklin** [comment]
That works.  Can I assume that destination is also an iterable of array-like things?

**Comment by shoyer** [comment]
Seems safe to me. Probably a good idea to verify matching lengths/shapes just be careful.
