### ISSUE TITLE
Global or context managed threadpools

### ISSUE THREAD

**Issue by shoyer** [ContinuumIO/dask#86]
Sometimes, it's difficult to avoiding doing a bit of blocking computation (e.g., to calculate dtypes #64).

With the current implementation of dask, it takes about 100 ms to start up a threadpool to start executing tasks, unless I manually specify the basic `get` method. I suspect we could eliminate most of this delay if we only created the threadpool once.

Two possible solutions:

1. Create a global threadpool the first time the relevant `compute` method is used. This is a little unclean, but would be highly practical. I think `numexpr` does something like this.
2. Create a context manager to mark blocks of computation that should use the same pool, e.g.,

    ```python
    with dask.pooled:
        assert x.dtype == float
        assert (x > 0).all()
        x.store(dest)
  ```

**Comment by mrocklin** [comment]
We could roll this in to the `set_options` PR we just merged

```python
pool = ThreadPool()
with set_options(pool=pool):
    ...
```
